### ISSUE TITLE
FluentMigrator.DotNet.Cli --no-connection throws exception

### ISSUE THREAD

**Issue by groogiam** [fluentmigrator/fluentmigrator#957] opened 2018-11-20 04:29 UTC
I am trying to generate a migration script without a live database running. The following command results in an exception.

`dotnet-fm migrate -p Postgres --no-connection -a Migrations.dll -o=db.sql`

```text
-------------------------------------------------------------------------------
2018111900: Migration2018111900 migrating
-------------------------------------------------------------------------------

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection.GetPoolAndSettings()
   at FluentMigrator.Runner.Processors.GenericProcessorBase.<>c__DisplayClass6_1.<.ctor>b__1() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.Core/Processors/GenericProcessorBase.cs:line 102
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FluentMigrator.Runner.Processors.GenericProcessorBase.EnsureConnectionIsOpen() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.Core/Processors/GenericProcessorBase.cs:line 128
   at FluentMigrator.Runner.Processors.GenericProcessorBase.BeginTransaction() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner.Core/Processors/GenericProcessorBase.cs:line 146
   at FluentMigrator.Runner.MigrationScopeHandler.BeginScope() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/MigrationScopeHandler.cs:line 37
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/MigrationRunner.cs:line 519
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/MigrationRunner.cs:line 365
   at FluentMigrator.Runner.Initialization.TaskExecutor.Execute() in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.Runner/Initialization/TaskExecutor.cs:line 165
   at FluentMigrator.DotNet.Cli.Commands.BaseCommand.ExecuteMigrations(MigratorOptions options, IConsole console) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.DotNet.Cli/Commands/BaseCommand.cs:line 32
   at FluentMigrator.DotNet.Cli.Commands.Migrate.OnExecute(IConsole console) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.DotNet.Cli/Commands/Migrate.cs:line 35
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 86
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 64
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 97
   at FluentMigrator.DotNet.Cli.Program.Main(String[] args) in /home/travis/build/fluentmigrator/fluentmigrator/src/FluentMigrator.DotNet.Cli/Program.cs:line 35
```

**Comment by jzabroski** [comment] 2019-03-01 21:20
I think this is a bit incorrect.  @groogiam  is using the `PreviewOnly` state, but his command line parameters actually use two options - `PreviewOnly` and `NoConnection`.

I guess I'm not clear on what the concept of an "Active Migration Scope" is intended to achieve.  Can you nest scopes, the same way you can nest SQL transactions?

The code is a bit hard for me to read.  I'm looking into it because we're still on FM 1.8 and I want to get us to the new hotness, but we have problems upgrading to FM 3 due to dotnet tools experience.

**Comment by fubar-coder** [comment] 2019-03-04 09:14
@jzabroski It's a concept I inherited: The active migration scope is de facto a transaction scope where each scope might be a *real* transaction or a "no-op transaction". It's all handled via the `MigrationScopeHandler`.

IOW: It's main purpose is to be able to configure whether we want to use a single transaction spanning multiple migrations or a transaction per migration. When we use a single transaction for multiple migrations, the the per-migration scopes are "no-op scopes". But when we use per-migration transactions, the the outer scope becomes a "no-op scope".

IMHO this is some kind of over-engineering that I'd like to get rid off as soon as I can think about something simpler 😀 .

**Comment by fubar-coder** [comment] 2019-04-23 07:40
Fixed in 3.2.1

**Closed by fubar-coder** 2019-04-23 07:40 UTC
Labels: bug

**Comment by igitur** [comment] 2020-02-03 15:31
Hi

Just upgraded from v3.1.3 to v3.2.1 and I noticed that 156f5f6723e6e7ffb00909e8115b976fa7a9da3b broke something for me. I'm also generating a `.sql` file containing all my migrations, but I would like each migration to be wrapped in a `BEGIN TRANSACTION` and `COMMIT TRANSACTION` in the output SQL. 

After 156f5f6723e6e7ffb00909e8115b976fa7a9da3b  this `BeginScope();` is never called so I don't see the transaction statements in my generated SQL anymore. To me, this is a breaking change/regression.

**Comment by jzabroski** [comment] 2020-02-10 21:41
@igitur Thanks for mentioning this.  I opened a new ticket.  In the future, consider opening a ticket as I almost lost track of this.  I was on vacation for one week.  If I was on vacation for two, my brain probably would've been too foggy to remember your comment in this email :) LOL
