### ISSUE TITLE
Obtain database type in fluent syntax

### ISSUE THREAD

**Issue by rhegner** [fluentmigrator/fluentmigrator#1741] opened 2024-03-11 22:06 UTC
**Is your feature request related to a problem? Please describe.**
In our project we created some extension methods to deal with custom data types like this:
```
public static TNext AsMyLatin1Guid<TNext>(this IColumnTypeSyntax<TNext> columnTypeSyntax) where TNext : IFluentSyntax
    => columnTypeSyntax.AsCustom("char(36) CHARACTER SET latin1");
```

In our migrations we're using these extension methods like this:
```
Create.Table("user")
    .WithColumn("user_id").AsMyLatin1Guid().PrimaryKey("pk_user");
```

This works fine as long as we're using only a single database type (MySql in this case).

Now we'd like to run our migrations on a SqLite database as well. So our extension method should return custom type specifications based on the database type. But it does not seem to be possible to obtain the database type within such an extension method.

**Describe the solution you'd like**
The preferred solution would be to be able to access the current database type from within such an extension method, for example like this (pseudo code):
```
public static TNext AsMyLatin1Guid<TNext>(this IColumnTypeSyntax<TNext> columnTypeSyntax) where TNext : IFluentSyntax
{
    if (columnTypeSyntax.DatabaseType == "MySql")
        return columnTypeSyntax.AsCustom("char(36) CHARACTER SET latin1");
    else
        return columnTypeSyntax.AsCustom("char(36)");
}
```

**Additional context**
Of course hints for a different way to solve this problems would be appreciated. We could probably obtain the current database type somehow on the migration level and then pass that as an additional parameter to these extensions methods. But that's not really a nice solution.

**Is this a feature you'd like to submit a PR for?**
I tried, but I did not get very far. I added a `DatabaseType` property to the `IColumnTypeSyntax` interface. It looks like there is only one place where that property needs to be implemented: `ExpressionBuilderWithColumnTypesBase`. But I have no clue how to obtain the database type in that class.

**Comment by fubar-coder** [comment] 2024-03-12 19:10
This is what I did when I needed to support a "JSON" column, but it should be usable for your situation too: I created a custom `IColumnsConvention`.

Example:

```c#
class MyCustomColumnConvention : IColumnsConvention {
  private readonly string _databaseType;

  public MyCustomColumnConvention(IProcessorAccessor processorAccessor) {
    _databaseType = processorAccessor.Processor.DatabaseType.ToLowerInvariant();
  }

  public IColumnsExpression Apply(IColumnsExpression expression) {
    var jsonColumns = expression.Columns
      .Where(x => string.Equals("json", x.CustomType, StringComparison.OrdinalIgnoreCase))
      .ToList();
    if (jsonColumns.Count == 0) {
      return expression;
    }

    if (_databaseType == "sqlserver2016") {
      foreach (var column in jsonColumns) {
        column.CustomType = null;
        column.Type = DbType.String;
        column.Size = int.MaxValue;
      }
    }

    return expression;
  }
}
```

**Comment by schambers** [comment] 2024-03-19 01:38
Do you think your comment would be useful in the documentation @fubar-coder? I can create an issue to add this example there. This is a good work around it seems.

**Comment by fubar-coder** [comment] 2024-03-20 09:30
Yes, it might be a good idea, but a **full** example is needed to be a usable example, which requires either:

- Querying the scoped `IConventionSet` service and add your own `IColumnsConvention` the the set
- A custom `IConventionSet` as scoped service, which should be derived from `DefaultConventionSet`, have only one public constructor, and the custom `IColumnsConvention` must be added to the `ColumnsConventions` property

The first one works better when the developer relies on behavior of the `IConventionSetAccessor` implementation (`AssemblySourceConventionSetAccessor`), while the second is better if you prefer **not** to rely on assembly scanning.

**Comment by schambers** [comment] 2024-03-21 01:15
How does this look @fubar-coder, I'm unsure of option 2 and was contemplating leaving it as it appears but open to suggestions: https://github.com/fluentmigrator/documentation/commit/7082a1335134a719daaf1ce35cb2cff7ca823986

**Comment by jzabroski** [comment] 2024-03-24 17:30
Duplicate of https://github.com/fluentmigrator/fluentmigrator/issues/1032

**Comment by schambers** [comment] 2024-03-24 19:50
I'll close this as I have an issue on the documentation repo to cover this documnetation: https://github.com/fluentmigrator/documentation/issues/75

We could move any discussion there

**Closed by schambers** 2024-03-24 19:50 UTC
Labels: feature
