### ISSUE TITLE
Specifying a utf8mb4 collation on mariadb 10.6 or later fails

### ISSUE THREAD

**Issue by braveyp** [fluentmigrator/fluentmigrator#1575] opened 2022-04-05 16:35 UTC
**Describe the bug**

Creating any string column with a utf8mb4 collation fails with an error message even when both server and client are set to use the utf8mb4 character set in my.ini

COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8mb3'

**To Reproduce**

Due to dependency issues you can only reproduce this in an in-process runner that has used assembly bindings to update to mysql.data.8.0.28.

Create a migration with the payload:

Create.Table("weebles").WithColumn("wobble"),AsString(255, "utf8mb4_unicode_ci");

**Expected behavior**
Fluent migrator should respect the server character set setting instead of using utf8mb3 or have a way to override the table character set.

**Information (please complete the following information):**
 - OS: windows
 - Platform .net 4.8
 - FluentMigrator version 3.3.2
 - FluentMigrator runner  "in-process runner"
 - Database Management System MariaDB
 - Database Management System Version 10.6 or 10.7

**Additional context**
This isn't a fluentmigrator bug as such but it's a by product of the fact that MariaDB changed the way they handle utf8 in 10.6 and later and they now map utf8 to utf8mb3 and now all system results (row counts etc) are returned as utf8mb3 even if the server character set is utf8mb4. They also appear to have made collations stricter so whereas in 10.5 you could specify a collation irrespective of the character set it will now fail if the collation is not part of the character set. 

If you create the tables within a script inside a migration with the utf8mb4 collations then this succeeds, it only fails if you use the Create.Table syntax. You can work around the issue by changing the AsString call to AsCustom("varchar(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci")

**Comment by jzabroski** [comment] 2022-04-17 19:17
Can you show me how this should work with just the Mysql driver? Like a hello world program. 

```
CREATE TABLE HelloWorldLog
(
  Name nvarchar(255) utf8mb4_unicode_ci 
);
```

```
var cmd = $@"INSERT into HelloWorldLog ([Name])
VALUES('{System.Threading.Thread.CurrentThread.CurrentPrincipal}'");
```

**Comment by jzabroski** [comment] 2022-04-22 15:50
@braveyp It sounds like MySQL 8 introduced utf8mb4 as the default character set.  Thus, can you reproduce this issue on a local machine running a docker MySQL 8 db?

Example article I found: https://www.codeproject.com/Articles/5328564/Easily-Convert-All-MySQL-Databases-Tables-To-utf8m

**Comment by jzabroski** [comment] 2022-04-22 15:54
> **This isn't a fluentmigrator bug as such**

Agree.

> but it's a by product of the fact that MariaDB changed the way they handle utf8 in 10.6 and later and they now map utf8 to utf8mb3 and now all system results (row counts etc) are returned as utf8mb3 even if the server character set is utf8mb4. They also appear to have made collations stricter so whereas in 10.5 you could specify a collation irrespective of the character set it will now fail if the collation is not part of the character set.

Actually, I think you are trying to solve an x-y problem.  I am not 100% positive, but it sounds like the codeproject article I linked above tells you what the trivial solution is for MySQL 8 - convert every table to utf8mb4 first, then run additional migrations.

You can use Execute.WithConnection to run the sample codeproject code and convert your database.  You may need to coordinate with other consumers of your application.  It's not fun.  Perhaps there are other solutions, but this should definitely work.  Are there technical reasons why this would not work, or is it just time-budget resource constraints that you want FluentMigrator to do something about it?

**Comment by jzabroski** [comment] 2022-05-03 14:45
@braveyp any update?

**Comment by vmandic** [comment] 2023-07-12 10:14
I am just in midst of upgrading from 10.3 to 10.6.14 of MariaDb and I am getting an error I can not surpass with FluentMigrator CLI tool calling my dll:

Seems related as it checks my "version_info" table which I use for tracking versions with FluentMigrator.

```bash
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '28521' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.MySqlField.set_CharacterSetIndex(Int32 value)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlCommand.ResetReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.Exists(String template, Object[] args) in D:\a\1\s\src\FluentMigrator.Runner.MySql\Processors\MySql\MySqlProcessor.cs:line 130
   at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.TableExists(String schemaName, String tableName) in D:\a\1\s\src\FluentMigrator.Runner.MySql\Processors\MySql\MySqlProcessor.cs:line 66
   at FluentMigrator.Runner.VersionLoader.get_AlreadyCreatedVersionTable() in D:\a\1\s\src\FluentMigrator.Runner\VersionLoader.cs:line 161
   at FluentMigrator.Runner.VersionLoader.LoadVersionInfo() in D:\a\1\s\src\FluentMigrator.Runner\VersionLoader.cs:line 177
   at FluentMigrator.Runner.VersionLoader..ctor(IProcessorAccessor processorAccessor, IConventionSet conventionSet, IMigrationRunnerConventions conventions, IVersionTableMetaData versionTableMetaData, IMigrationRunner runner) in D:\a\1\s\src\FluentMigrator.Runner\VersionLoader.cs:line 118
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.FluentMigratorServiceCollectionExtensions.<>c.<AddFluentMigratorCore>b__0_6(IServiceProvider sp) in D:\a\1\s\src\FluentMigrator.Runner\FluentMigratorServiceCollectionExtensions.cs:line 159
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FluentMigrator.Runner.MigrationRunner.get_VersionLoader() in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 347
   at FluentMigrator.Runner.MigrationRunner.IsMigrationStepNeededForUpMigration(IMigrationInfo migration, Int64 targetVersion) in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 473
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass60_0.<GetUpMigrationsToApply>b__0(KeyValuePair`2 pair) in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 457
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement) in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 423
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement) in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 399
   at FluentMigrator.Runner.MigrationRunner.MigrateUp() in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 390
   at FluentMigrator.Runner.Initialization.TaskExecutor.Execute() in D:\a\1\s\src\FluentMigrator.Runner\Initialization\TaskExecutor.cs:line 168
   at FluentMigrator.DotNet.Cli.Commands.BaseCommand.ExecuteMigrations(MigratorOptions options, IConsole console) in D:\a\1\s\src\FluentMigrator.DotNet.Cli\Commands\BaseCommand.cs:line 29
   at FluentMigrator.DotNet.Cli.Commands.Migrate.OnExecute(IConsole console) in D:\a\1\s\src\FluentMigrator.DotNet.Cli\Commands\Migrate.cs:line 32
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
   at FluentMigrator.DotNet.Cli.Program.Main(String[] args) in D:\a\1\s\src\FluentMigrator.DotNet.Cli\Program.cs:line 49
error Command failed with exit code 134.

```

**Comment by jzabroski** [comment] 2023-09-04 15:26
@vmandic I think your problem is caused by a dll version conflict. This seems completely unrelated to this issue.

**Comment by jzabroski** [comment] 2023-11-25 02:47
Resolved in latest release coming this week.  Issue was MariaDB requires a newer dll version.  Using #1678 should address.  Re-open if I am incorrect.

**Closed by jzabroski** 2023-11-25 02:47 UTC
