### ISSUE TITLE
Issue on CreateIndex VersionInfo with non-default schema

### ISSUE THREAD

**Issue by sindrunas** [fluentmigrator/fluentmigrator#764] opened 2016-12-27 17:55 UTC
I'm trying to set a default schema extending the VersionTable class, but I figured out there seems to be a bug preventing me to achive that.
When the migrator tries to create the UC_VERSION unique index it fails because it's not using the schema defined in SchemaName.

This is the error:
[+] CreateIndex VersionInfo (Version)
CREATE UNIQUE INDEX UC_Version ON VersionInfo (Version ASC)    
!!! ORA-00942: table or view does not exist
!!! ORA-00942: table or view does not exist

Since the creation of the table VersionInfo is using the scheme defined in SchemaName but the creation of the unique is not, it fails.

Here is my VersionTable class:

[VersionTableMetaData]
    public class VersionTable : DefaultVersionTableMetaData
    {
        public override string SchemaName
        {
            get { return "MYSCHEMA"; }
        }
    }

**Comment by eloekset** [comment] 2016-12-27 20:48
Did you experience this using version 1.6.2 of FluentMigrator? I just tested it now, and it seems to work fine in my environment.
<img width="833" alt="2016-12-27_21-45-33" src="https://cloud.githubusercontent.com/assets/791721/21508066/0de8f568-cc7e-11e6-908f-cf1aab7278d2.png">
<img width="859" alt="2016-12-27_21-41-44" src="https://cloud.githubusercontent.com/assets/791721/21508067/1365ec76-cc7e-11e6-9202-f3059d24af04.png">

**Comment by sindrunas** [comment] 2016-12-27 20:53
Yes, I'm using version 1.6.2 with OracleManaged driver. May it be the problem? 

Thank you

**Comment by eloekset** [comment] 2016-12-27 21:14
I don't know a way to test with that driver. But if you run the console runner with option --verbose=true, you'll see the SQL statements that are executed using the Oracle generator. An example for SQL Server:
`migrate -a=FluentCustomSchema\bin\Debug\FluentCustomSchema.dll -db=SqlServer -conn="Data Source=(local)\SQL2016;Initial Catalog=Test1Db;Integrated Security=true" --verbose=true`
<img width="487" alt="2016-12-27_22-11-22" src="https://cloud.githubusercontent.com/assets/791721/21508487/bfaeaf88-cc81-11e6-8dab-97704159abb9.png">

**Comment by eloekset** [comment] 2016-12-27 21:27
Referring to the unit tests, it sure looks like the Oracle generator has an issue generating CREATE INDEX with custom schema.
<img width="795" alt="2016-12-27_22-18-32" src="https://cloud.githubusercontent.com/assets/791721/21508612/ae87042a-cc82-11e6-8f41-ee8a257c3e8b.png">

This test was created in commit 2cdca801.

Scrolling through the tests in that commit, it seems like a lot of generators ignore the custom schema. At least at that time. But the Oracle test still is like this.

**Comment by eloekset** [comment] 2016-12-27 21:49
Also #752 and #542 are about this.

**Comment by CennetDemir** [comment] 2016-12-29 12:08
Hello, try updating your version table meta data as following, your problem is about case sensitity, set OWNS_SCHEMA feature as well

[VersionTableMetaData]
    public class VersionTable : DefaultVersionTableMetaData
    {

        public override bool OwnsSchema
        {
            get { return true; }
        }

        public override string TableName
        {
            get
            {
                return "VERSIONINFO";
            }
        }
        public override string SchemaName
        {
            get { return "MY_SCHEMA"; }
        }

        public override string UniqueIndexName
        {
            get
            {
                return "UC_VERSION";
            }
        }

        public override string AppliedOnColumnName
        {
            get
            {
                return "APPLIEDON";
            }
        }

        public override string ColumnName
        {
            get
            {
                return "VERSION";
            }
        }

        public override string DescriptionColumnName
        {
            get
            {
                return "DESCRIPTION";
            }
        }
    }

**Comment by sindrunas** [comment] 2017-01-02 16:39
Unfortunately it did not work. The runner is still ignoring the schema when tries to create the unique index.

The generated SQL is "CREATE UNIQUE INDEX UC_VERSION ON VERSIONINFO" instead of "CREATE UNIQUE INDEX UC_VERSION ON **_MYSCHEMA_**.VERSIONINFO"

**Comment by basarolgun** [comment] 2017-12-06 00:21
i am facing same problem that using version 1.6.2 of FluentMigrator, and the driver is NHibernate.Driver.OracleManagedDataClientDriver. 
Is there any comment ?

**Comment by basarolgun** [comment] 2017-12-06 00:35
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01950: 'USERS' table ... permissom error...

SELECT 1 FROM USER_TABLES WHERE upper(TABLE_NAME) = 'VERSİONINFO'

**Comment by fubar-coder** [comment] 2018-04-13 12:27
The schema handling of ORACLE (and other databses) was streamlined and this problem should be fixed in 2.0.0. Please leave a comment if the issue is still there after the 2.0 release.

**Closed by fubar-coder** 2018-04-13 12:27 UTC
Labels: Bug, db:oracle
