### ISSUE TITLE
Fluent not preserving comments

### ISSUE THREAD

**Issue by bhawkbamboo** [fluentmigrator/fluentmigrator#973] opened 2018-12-17 22:46 UTC
If you run a .sql file that creates a stored procedure or alters one and that file contains sql comments -- those are not deployed to the database. If you do the same thing thru SQL server management the comments are preserved.

**Comment by fubar-coder** [comment] 2018-12-18 08:09
Duplicate of #956

**Closed by fubar-coder** 2018-12-18 08:09 UTC
