### ISSUE TITLE
Fluentmigrator throws error while running migration for a RDS mysql db instance to DB engine version 8.0.30 or above

### ISSUE THREAD

**Issue by Diwa-2010** [fluentmigrator/fluentmigrator#1670] opened 2023-08-14 15:21 UTC
**Describe the bug**
Fluentmigrator throws error while run migration for a RDS mysql db instance to DB engine version 8.0.31

 Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '26996' was not present in the dictionary.
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
       at MySql.Data.MySqlClient.MySqlField.set_CharacterSetIndex(Int32 value)
       at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
       at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
       at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
       at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
       at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
       at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
       at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
       at MySql.Data.MySqlClient.MySqlDataReader.Close()
       at MySql.Data.MySqlClient.MySqlCommand.ResetReader()
       at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
       at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
       at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
       at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.Exists(String template, Object[] args) in D:\a\1\s\src\FluentMigrator.Runner.MySql\Processors\MySql\MySqlProcessor.cs:line 130
       at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.TableExists(String schemaName, String tableName) in D:\a\1\s\src\FluentMigrator.Runner.MySql\Processors\MySql\MySqlProcessor.cs:line 66
       at FluentMigrator.Runner.VersionLoader.get_AlreadyCreatedVersionTable() in D:\a\1\s\src\FluentMigrator.Runner\VersionLoader.cs:line 161
       at FluentMigrator.Runner.VersionLoader.LoadVersionInfo() in D:\a\1\s\src\FluentMigrator.Runner\VersionLoader.cs:line 174
       at FluentMigrator.Runner.VersionLoader..ctor(IProcessorAccessor processorAccessor, IConventionSet conventionSet, IMigrationRunnerConventions conventions, IVersionTableMetaData versionTableMetaData, IMigrationRunner runner) in D:\a\1\s\src\FluentMigrator.Runner\VersionLoader.cs:line 119
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
       at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
       at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
       at Microsoft.Extensions.DependencyInjection.FluentMigratorServiceCollectionExtensions.<>c.<AddFluentMigratorCore>b__0_6(IServiceProvider sp) in D:\a\1\s\src\FluentMigrator.Runner\FluentMigratorServiceCollectionExtensions.cs:line 159
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
       at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
       at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
       at System.Lazy`1.CreateValue()
       at FluentMigrator.Runner.MigrationRunner.ListMigrations() in D:\a\1\s\src\FluentMigrator.Runner\MigrationRunner.cs:line 914
       at FluentMigrator.Runner.Initialization.TaskExecutor.Execute() in D:\a\1\s\src\FluentMigrator.Runner\Initialization\TaskExecutor.cs:line 188
       at FluentMigrator.DotNet.Cli.Commands.BaseCommand.ExecuteMigrations(MigratorOptions options, IConsole console) in D:\a\1\s\src\FluentMigrator.DotNet.Cli\Commands\BaseCommand.cs:line 32
       at FluentMigrator.DotNet.Cli.Commands.ListMigrations.OnExecute(IConsole console) in D:\a\1\s\src\FluentMigrator.DotNet.Cli\Commands\ListMigrations.cs:line 30
    --- End of stack trace from previous location where exception was thrown ---
       at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
       at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
       at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
       at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
       at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
       at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
       at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
       at FluentMigrator.DotNet.Cli.Program.Main(String[] args) in D:\a\1\s\src\FluentMigrator.DotNet.Cli\Program.cs:line 46

We've done some investigation and found that it could happen due to Fluentmigrator still uses the MySql.Data version 8.0.28 [here](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.DotNet.Cli/FluentMigrator.DotNet.Cli.csproj#L20C5-L20C63).

This works as prefect if we tried to upgrade to db engine version 8.0.28. 

**To Reproduce**
Upgrade a MYSQL RDS DB engine version to 8.0.30 or above and run a migration using Fluentmigrator

**Expected behavior**
Fluentmigrator should run a migration in a db instance version to 8.0.31 or above without an any issue.

**Information (please complete the following information):**
 - OS: Amazon RDS MYSQL 
 - Platform : .NET Framework 4.6.2
 - FluentMigrator version : 3.3.2
 - FluentMigrator runner: FluentMigrator.DotNet.Cli
 - Database Management System : Mysql
 - Database Management System Version 

**Additional context**

**Comment by jzabroski** [comment] 2023-11-25 03:03
Fixed by #1678

**Closed by jzabroski** 2023-11-25 03:03 UTC

**Comment by gwin003** [comment] 2023-12-05 17:51
@jzabroski Sorry to bring up a closed thread, but are we waiting for a the release of 5.0.0 to fix this issue? I'm running into this exact same error, and might have to downgrade our version of MySQL on RDS in the meantime.

**Comment by jzabroski** [comment] 2023-12-05 17:58
No worries. Yes, that is the hold up. You can use the 4.0 alpha release in Azure devops nuget feed if urgent. Think I will release 5.0 this weekend. Just need to write up the release notes.

**Comment by gwin003** [comment] 2023-12-05 18:12
Thanks for the quick update! I'll hold off doing anything drastic on my end for now and keep an eye on the release.

**Comment by jzabroski** [comment] 2023-12-14 00:28
It's released

**Comment by gwin003** [comment] 2023-12-14 19:25
Already pulled the new version into my project and can confirm the issue is fixed. Thanks for your work on this!

**Comment by jzabroski** [comment] 2023-12-15 05:01
A lot of credit goes to @lillo42
