### ISSUE TITLE
issue with Update.Table with other then default schema using OracleGenerator

### ISSUE THREAD

**Issue by karabiberoglu** [fluentmigrator/fluentmigrator#752] opened 2016-12-05 08:19 UTC
when i run migrations over Oracle, i faced with an issue. When you update or delete data from another schema's table, it did not work.

if you use Update.Table with InSchema method, schema property is ignoring. Thus generated script is not executing because table's schema is different.

For example,

`Update.Table("TEST_TABLE")
                .InSchema("TEST_SCHEMA")
                .Set(new { TEST_COLUMN = 1 })
                .Where(new { TEST_COLUMN = 0 });`

Generated script is 

> UPDATE TEST_TABLE SET TEST_COLUMN = 1 WHERE TEST_COLUMN = 0

but it should be 

> UPDATE TEST_SCHEMA.TEST_TABLE SET TEST_COLUMN = 1 WHERE TEST_COLUMN = 0

Actually same issue is exist when using Delete.FromTable.

Regards

**Comment by CennetDemir** [comment] 2016-12-29 12:09
this issue is not relevant with #764 , #764 is occuring because of case sensitivity and ownsSchema attirbute

**Comment by CennetDemir** [comment] 2016-12-29 12:09
i face with the same issue here

**Comment by fubar-coder** [comment] 2018-04-13 12:27
The schema handling of ORACLE (and other databses) was streamlined and this problem should be fixed in 2.0.0. Please leave a comment if the issue is still there after the 2.0 release.

**Closed by fubar-coder** 2018-04-13 12:27 UTC
Labels: Bug, db:oracle
