### ISSUE TITLE
IfDatabase("SqlServer") matches "SqlServerCE" database type

### ISSUE THREAD

**Issue by stonkie** [fluentmigrator/fluentmigrator#422] opened 2013-06-03 01:21 UTC
When using the IfDatabase() method, "SqlServer" matches "SqlServerCE" and "SqlServer2000". It is impossible to execute an operation for SQLServer but not for SQLServerCE using the IfDatabase() method.

This is because the IfDatabaseExpressionRoot.DatabaseTypeApplies() method uses StartsWith() instead of Equals() to compare the database type names.

Is this "by design"?

**Comment by detoxhby** [comment] 2017-08-30 19:01
The issue still exists and makes it impossible to distinguis between those database types.

The most awkward part is that SqlServerCe has tons of unsupported operations and throws exception, so its not even possible to silently ignore it.

The real problem lies here: https://github.com/fluentmigrator/fluentmigrator/blob/f17dca3ba0ada883bf016d7bf297c9e0b8b8bdf7/src/FluentMigrator.Runner/Processors/SqlServer/SqlServerProcessor.cs#L41
Every SqlServer up from 2005 will have this processor and would report only this to IfDatabase check.

Easy fixup would be to expose originally the used database provider for migrations to make decision based on that.

**Comment by fubar-coder** [comment] 2018-04-10 21:33
Duplicate of #387.
Workaround in release 2.0.0 is to use `IfDatabase` with predicate.

**Closed by fubar-coder** 2018-04-10 21:33 UTC
Labels: Bug
