### ISSUE TITLE
Can not resolve reference `Microsoft.Identity.Client` on Xamarin.Forms

### ISSUE THREAD

**Issue by m4rkyx** [fluentmigrator/fluentmigrator#1486] opened 2021-05-31 12:48 UTC
When updating from 3.2.15 to 3.2.16 our Xamarin.Forms solution cannot build because of the current error :
`
Can not resolve reference: Microsoft.Identity.Client, referenced by Microsoft.Data.SqlClient. Please add a NuGet package or assembly reference for Microsoft.Identity.Client, or remove the reference to Microsoft.Data.SqlClient.	
`

Works perfectly with version 3.2.15.
We don't want to add the specified nuget package so we will stick with version 3.2.15.

**Information:**
 - OS: Windows 10, Android
 - Platform: Net Standard 2.0
 - FluentMigrator version 3.2.16
 - FluentMigrator runner : 3.2.16
 - Database Management System : SQLite

**Comment by jzabroski** [comment] 2021-06-11 16:07
There were no SQLite specific features added in 3.2.15 so that should be fine for now.  Thanks for reporting this.

I have not built a Xamarin Forms application before.  Can you tell me how to set that up?  It looks like the Xamarin.Forms Todo app uses SQLite.  https://github.com/xamarin/xamarin-forms-samples/tree/main/Todo

Separately, can you tell me what TFM you're using when you say your Xamarin.Forms solution cannot build?  Could it be as simple as you have put third party stuff in a specific TFM when it should go in a more general TFM so it can be transitively included?

**Comment by m4rkyx** [comment] 2021-06-17 07:25
> I have not built a Xamarin Forms application before. Can you tell me how to set that up? It looks like the Xamarin.Forms Todo app uses SQLite. https://github.com/xamarin/xamarin-forms-samples/tree/main/Todo
>
> Separately, can you tell me what TFM you're using when you say your Xamarin.Forms solution cannot build? Could it be as simple as you have put third party stuff in a specific TFM when it should go in a more general TFM so it can be transitively included?

We're targeting .net standard 2.0 in our solution and we are using the `Mono.Data.Sqlite.dll` (included with Xamarin SDK) instead of the package `sqlite-net-pcl` provided in the Xamarin.Forms Todo. Maybe the use of this dll could lead to this error.

**Comment by jzabroski** [comment] 2024-03-18 17:20
@schambers Can you review closing this? Looks like it was a dll incompatibility issue and other people have not had the same experience.

**Comment by schambers** [comment] 2024-03-18 17:23
Will do! I'll get to it later today

**Comment by jzabroski** [comment] 2024-07-02 20:29
Closing. There was not enough information to reproduce the problem. That being said, FluentMigrator 5.0 decouples runners, so SqlClient should not longer be needed for Sqlite users, ergo it is likely no longer reproducible on FluentMigrator 5.0+

**Closed by jzabroski** 2024-07-02 20:29 UTC
Labels: bug
