### ISSUE TITLE
Anyway to specify client cert in connection string?

### ISSUE THREAD

**Issue by sashang** [fluentmigrator/fluentmigrator#985] opened 2019-02-09 04:05 UTC
I'm trying to use migrate.exe to run my migrations against postgres in google cloud. The postgres server has ssl certs enabled, so I need to pass a client cert, but I can't because I see no parameter in the connection string that can take a client key. THis is the command line I'm using:

```
mono ../../packages/FluentMigrator.Console/net461/any/Migrate.exe  -c "Host=35.236.69.84;Database=titan_dev;Username=sashang;Password=<password>;SSL Mode=Require;Trust Server Certificate=true" --provider Postgres -a bin/Debug/netcoreapp2.2/Dev.dll    --task migrate:up
-------------------------------------------------------------------------------
=============================== FluentMigrator ================================
-------------------------------------------------------------------------------
Source Code:
  https://github.com/fluentmigrator/fluentmigrator
Ask For Help:
  https://gitter.im/FluentMigrator/fluentmigrator
-------------------------------------------------------------------------------
Using connection string Host=35.236.69.84;Database=titan_dev;Username=sashang;Password=********;SSL Mode=Require;Trust Server Certificate=true
!!! 28000: connection requires a valid client certificate
sashan@deimos titan/src/Dev master 3☠  > 
```
How can I get around this?

**Comment by fubar-coder** [comment] 2019-02-11 11:54
That's not supported yet (duplicate of #968). I added a workaround using the in-process migrator to #968.

**Closed by fubar-coder** 2019-02-11 11:54 UTC
