### ISSUE TITLE
FluentMigrator.Console 3.2.4 nuget package has dependencies

### ISSUE THREAD

**Issue by alexeimatrosov** [fluentmigrator/fluentmigrator#1209] opened 2020-04-08 09:59 UTC
FluentMigrator.Console 3.2.4 nuget package has dependencies, unlike previous versions.
This makes the package not really usable by Octopus Deploy as it doesn't support referencing packages with dependencies.

Is that intentional to make FluentMigrator.Console nuget packages to have dependencies from now on or not?

Thank you!
![Untitled](https://user-images.githubusercontent.com/2151138/78771359-b8c30580-7998-11ea-858a-391fd00c6bc5.png)

**Comment by jzabroski** [comment] 2020-04-08 13:47
@fubar-coder  I'm not sure why this happened.  This is the first time I've packed and upload the nuget packages.  Any ideas?

**Comment by jzabroski** [comment] 2020-04-08 13:50
@alexeimatrosov Can you export your Octopus Deploy step template?  I use Octopus Deploy as well except I install `dotnet-fm` through `dotnet.exe`.  I only use the Console for MSBuild purposes, and that's way off-topic here.

Separately, seems like your step template has a bug as it is silently failing.

**Comment by alexeimatrosov** [comment] 2020-04-08 14:44
@jzabroski,
The actual step is failing as `Migrate.exe` isn't found. When the path to `Migrate.exe` is fixed then it still fails. I attach another screenshot.

The screenshot I attached previously was of the step that pulls the package.

![Untitled](https://user-images.githubusercontent.com/2151138/78797537-82997c00-79c0-11ea-81f2-f67e76070c97.png)

[Octopus_Step_Template_Run_FluentMigrator_migrations.zip](https://github.com/fluentmigrator/fluentmigrator/files/4451055/Octopus_Step_Template_Run_FluentMigrator_migrations.zip)

**Comment by jzabroski** [comment] 2020-04-08 16:21
@alexeimatrosov Maybe true, but I'm just reminding you to reconfigure that step template for "Upload package" so it fails in that situation in the future.

As an immediate workaround, using dotnet-fm should work fine.  I realize that may be intractable if you're using net461.  I don't know why FluentMigrator.Console packaged differently on Nuget.org for 3.2.4.

The commands I used to build and pack were:

```powershell
git clean -xf
git checkout tags/v3.2.4
dotnet.exe pack -p:PackageVersion=3.2.4 -p:VersionNumber=3.2.4.0 -p:Version=3.2.4.0 -p:FileVersion=3.2.4.0 --Configuration Release -o .\packOutput
```
I then uploaded the contents of .\packOutput to nuget.org.

However, this is the first time I did the release myself.  Long-term Goal is to have AzureDevOps do the promotion for us.

**Comment by jzabroski** [comment] 2020-04-08 16:34
@alexeimatrosov I think this might be a clue.  3.2.1 was built when we were on Travis CI for builds.  Check out this part of the script, which does magic for FluentMigrator.Console.csproj:

https://github.com/fluentmigrator/fluentmigrator/blob/cdaf98552a71a3ce6b2d94431c98ac283efddc52/.travis.yml#L15-L20

Sorry about this.  I didn't understand what this portion of the script was trying to achieve, and your issue gives a good clue as to why it's doing what it's doing.  Looking at https://github.com/fluentmigrator/fluentmigrator/commit/218522e14158de8ef7bd8220c764ebe65378c94f , it seems the reason is that FluentMigrator.Console is the only way to support net461 assemblies using out-of-process runner.

**Comment by eloekset** [comment] 2020-04-08 23:07
I don't know if the 3.2.4 version published on nuget.org is built from the same commit as the DevOps build pipeline, but the same [package version exists on our new Azure Artifacts feed](https://dev.azure.com/fluentmigrator/fluentmigrator/_packaging?_a=package&feed=fluentmigrator%40Local&package=FluentMigrator.Console&protocolType=NuGet&version=3.2.4&view=overview) that's supposed to replace the current myget.org feed. The package looks like follows, and is built from commit https://github.com/fluentmigrator/fluentmigrator/commit/1065ef92559a06a9301846c5263fe1a67857e683
![image](https://user-images.githubusercontent.com/791721/78841744-759b7d80-79fe-11ea-9714-5b926ecdcc67.png)

**Comment by jzabroski** [comment] 2020-04-08 23:35
Yes, it's the same commit.  I did the equivalent of `git clean -xf && git checkout tags/v3.2.4`. If you do `git log` you'll see that 1064ef9 is the head commit.

The issue was I was asking @fubar-coder  about how to build it off my machine while the Azure Artifacts feed was still stabilizing, and I think I didn't ask him a broad enough question or look carefully/understand what the Travis CI steps were doing (3.2.1 is the last release on nuget.org and I believe used Travis CI build process).

I'm just waiting on Mark to provide his insight, then I'll probably delist 3.2.4 and publish a 3.2.5 hotfix.

**Comment by eloekset** [comment] 2020-04-09 10:38
If we can confirm that the 3.2.4 packages on Azure Artifacts are correct (e.g. works with Octopus, for this specific issue) the 3.2.5 package can be deployed to nuget.org from the release pipeline.

@alexeimatrosov, I think you can try to connect to the public Azure Artifacts feed and use the 3.2.4 package from that feed instead of the nuget.org one. If it works for you, we know that the next version will be fine to deploy to nuget.org. The feed's source is https://pkgs.dev.azure.com/fluentmigrator/fluentmigrator/_packaging/fluentmigrator/nuget/v3/index.json

**Comment by jzabroski** [comment] 2020-04-09 14:41
@eloekset  Yes, I agree.  @alexeimatrosov Can you please try adding a feed source in Visual Studio to https://pkgs.dev.azure.com/fluentmigrator/fluentmigrator/_packaging/fluentmigrator/nuget/v3/index.json  Once confirmed we should be able to fix this and release 3.2.5 hopefully this weekend.

**Comment by jzabroski** [comment] 2020-04-09 15:13
@eloekset I think I figured out what Mark did here.  See: https://github.com/fluentmigrator/fluentmigrator/commit/0b854af835f050840ee65e1852406dbac4dc85fd

What he's saying is that FluentMigrator.Console already ships the FluentMigrator binary compatible version, so that's why it doesn't make sense to declare it as an official "dependency".  Instead, it's an unlisted/implicit dependency, which is why FluentMigrator.Console can't be packed using [`dotnet pack --no-dependencies`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)

#### FluentMigrator.Console.3.2.1
![image](https://user-images.githubusercontent.com/447485/78909455-8aedc780-7a51-11ea-939b-a95e16c2d1c6.png)

#### FluentMigrator.Console.3.2.4

![image](https://user-images.githubusercontent.com/447485/78910541-20d62200-7a53-11ea-8fce-12927090af19.png)

**Comment by jzabroski** [comment] 2020-04-09 15:15
@eloekset I wonder if we mark all the `<PackageReference Include="SomePackage" Version="x.y.z.w" />` with `PrivateAssets="all"` if that could fix the issue, too, and simplify the packing process?  I don't have a good understanding of how all those Asset knobs work, though.

**Comment by jzabroski** [comment] 2020-04-09 21:19
@alexeimatrosov I delisted all 3.2.4 packages due to this issue and #1211 , and will focus this weekend on fixing things.  Your issue seems very straight forward, and the other issue might take a couple of hours to write regression tests to make sure whatever fix I put in actually works.

**Comment by jzabroski** [comment] 2020-04-09 21:23
@eloekset This blog post seems to cover the problem rather well: https://dev.to/wabbbit/include-both-nuget-package-references-and-project-reference-dll-using-dotnet-pack-2d8p

**Comment by alexeimatrosov** [comment] 2020-04-10 05:25
@jzabroski,
I checked manually content of the 3.2.4 package from https://pkgs.dev.azure.com/fluentmigrator/fluentmigrator/_packaging/fluentmigrator/nuget/v3/index.json and it looks good, should work during deployment. Unfortunately, I can't fiddle with Octopus' configuration to test it there.
For the time being I reverted to usage of 3.2.1 version.
Thank you!

**Comment by eloekset** [comment] 2020-04-10 10:12
Ok, so the way our Azure Pipeline builds this package is fine. We should just use our build and release pipelines to push NuGet packages instead of doing it manually. Or am I missing something?

**Comment by jzabroski** [comment] 2020-04-10 14:51
@eloekset I don't think we've successfully published a package from there to nuget.org.  So, I manually did it as I wasn't sure it was working.  I think you're right, that we should use that approach, but I also think that we should consider simplifying the build process if possible, too.  I think that for this weekend, all we need to do to release a 3.2.5 release successfully is bump the tag, and add an API Key for the organization (unless you already created one?).  If you haven't created one, I can create one and share the secret with Mark and you via my password manager app.

**Comment by eloekset** [comment] 2020-04-10 17:25
The API key is in place, but it has never been tested. Let's see if it works. Will you add the new tag?
![image](https://user-images.githubusercontent.com/791721/79009911-fb373e80-7b60-11ea-843b-47a7919ed5c0.png)

**Comment by jzabroski** [comment] 2020-04-10 17:42
I created the tag and the release is published here: https://github.com/fluentmigrator/fluentmigrator/releases/tag/v3.2.5

**Comment by eloekset** [comment] 2020-04-11 09:12
OMG, for some reason the version format has changed, so our pipelines didn't work this time. Will investigate it later today.
![image](https://user-images.githubusercontent.com/791721/79039969-514dc580-7be5-11ea-8b5f-5947a8a7e3e8.png)

It got version 3.3.0 instead of 3.2.5.

**Comment by eloekset** [comment] 2020-04-11 10:34
So far I think UseGitVersion task has changed, so it's not something we've done different this time. Comparing the logs for the v3.2.4 tag and the v3.2.5 tag the process started off differently. The one that worked like it should started off looking at tags and concluded that the latest tag should be used as base version, while the one that failed started off looking at commits instead and concluded to use 3.2.0 as base version.
![image](https://user-images.githubusercontent.com/791721/79041496-acd18080-7bf0-11ea-9b2a-003d10a2e893.png)
I will continue investigating this later.

**Comment by eloekset** [comment] 2020-04-11 14:33
Ref #1213 the GitVersion issue is fixed by sticking to version 5.1.3 of GitVersion. The build for my commit to the yml files got version number 3.2.6+1, but unfortunately, since the yml files for our build pipelines are in source control, it's impossible to get a working build pipeline for our older tag. I tried to trigger the pipeline for /refs/tags/v3.2.5 but then the old pipeline that uses the latest version of GitVersion runs.

That means, we'll have to create another release v3.2.6 just to get the version number correctly set for the next release.

**Comment by jzabroski** [comment] 2020-04-11 15:50
Wow!  Great work, Eivind!

**Comment by jzabroski** [comment] 2020-04-11 19:49
3.2.6 deployed

**Closed** 2020-04-11 19:49 UTC
Labels: tool:dotnet-console

**Comment by jzabroski** [comment] 2020-04-11 22:15
@alexeimatrosov Please verify, BTW.  I did my verification by using PeaZip to open the download of the nupkg from the FuGet gallery.  It appears to be identical to 3.2.4 modulo increase package size.

**Comment by alexeimatrosov** [comment] 2020-04-14 06:22
Thank you very much for your work!

@jzabroski, 
I reconfigured Octopus release to use `FluentMigrator.Console` `3.2.6` and it managed to pull the package nicely. Path to `Migrate.exe` needed to be changed, as there is `tools` directory in the NuGet package now.
However, running `Migrate.exe` providing it an assembly with migrations that was built referencing `FluentMigrator` `3.2.1` does fail with: `!!! No migrations found`
Is this expected behavior?

**Comment by jzabroski** [comment] 2020-04-14 12:50
@alexeimatrosov Unfortunately, yes.  See #1016 and my comments on why #1211 is a false positive (although still annoying).  I'm making progress towards improving this experience as part of #1178 and #1197 , but even then, I'll likely add a `DirtyAssemblyResolveHelper` that is opt-in via command-line flag.
