### ISSUE TITLE
Sqlite Creating Unique Constraint not working

### ISSUE THREAD

**Issue by fairking** [fluentmigrator/fluentmigrator#1492] opened 2021-07-07 13:00 UTC
**Describe the bug**
As we just found out the following line:
```
public override void Up()
        {
            Create.UniqueConstraint("uq_my_table").OnTable("my_table").Columns(new[] { "col1", "col2" });
        }
```
is not working with sqlite database. After the migration executed the constraint is missing in sqlite db and the duplicates are allowed.
However when I added extra line as a workaround, it created the expected constraint:
```
public override void Up()
        {
            Create.UniqueConstraint("uq_my_table").OnTable("my_table").Columns(new[] { "col1", "col2" });
            IfDatabase("sqlite").Execute.Sql("CREATE UNIQUE INDEX uq_my_table ON my_table(col1, col2);");
        }
```

**To Reproduce**
See description

**Expected behavior**
It must create an unique constraint

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Core 3.1
 - FluentMigrator version 3.2.17
 - FluentMigrator runner
 - Database Management System SQLite
 - Database Management System Version

**Additional context**
None

**Comment by jzabroski** [comment] 2021-07-14 20:38
Hi @fairking ,

Hmm... That's pretty weird.  I went to the changes log for SQLite and it looks like this feature has been around awhile:

> ### 2001-09-27 (2.0-alpha-3)
> SQLite now honors the UNIQUE keyword in CREATE UNIQUE INDEX. Primary keys are required to be unique.

I think the problem is here:
https://github.com/fluentmigrator/fluentmigrator/blob/9c87d698b161b3a1bb596a5624c02891a64459c5/src/FluentMigrator.Runner.SQLite/Generators/SQLite/SQLiteGenerator.cs#L108-L111

And the fact that SQLite is not set to Strict but Loose compatibility mode by default cf https://github.com/fluentmigrator/fluentmigrator/issues/812#issuecomment-383417163

I think the SQLiteGenerator code probably needs to be thrown out and replaced.

**Comment by Fungusware** [comment] 2021-08-23 03:47
Yes, this seem to be happening to me also.

Unique Constraint is not created and also Foreign Key create as

`            Alter.Table("Usage").AddColumn("LicenseId").AsInt32().Nullable().ForeignKey("License", "Id");`

Is not being applied.

**Comment by zelenij** [comment] 2021-12-24 01:07
I experience the same issue with unique constraints in Sqlite

**Comment by mattbrailsford** [comment] 2022-04-16 14:52
I'm implementing a fix for this here https://github.com/fluentmigrator/fluentmigrator/pull/1585 but just to point out, what you are asking for is already supported if you go via the `Create.Index` API (which is effectively what you are doing in you workaround).

In my PR I'm just converting "UNIQUE" constraint requests into "UNIQUE" index requests instead (and same for DROPs)

**Closed** 2022-04-16 19:51 UTC
Labels: db:sqlite
