### ISSUE TITLE
Oracle: define tablespace when creating an index.

### ISSUE THREAD

**Issue by barser** [fluentmigrator/fluentmigrator#667] opened 2015-10-22 08:29 UTC
Oracle: define tablespace when creating an index.

As far as I know, the separate tablespace containing all indices data is well-known solution for performance improvements. It would be helpful to add an opportunity for defining tablespace with fluent syntax.

**Comment by fubar-coder** [comment] 2018-03-31 21:39
Canj you provide more detailed information?

**Comment by jzabroski** [comment] 2020-05-19 19:31
Duplicate of #967 - @barser  This is absolutely on the roadmap to try to add this year.

**Closed by jzabroski** 2020-05-19 19:31 UTC
Labels: awaiting-answer, db:oracle, up-for-grabs
