### ISSUE TITLE
New maintainer requested

### ISSUE THREAD

**Issue by tommarien** [fluentmigrator/fluentmigrator#697] opened 2016-01-27 08:05 UTC
Hi,

As i am focusing on node.js development atm. I am requesting to have a new maintainer for this wonderful framework.

I any of you feels able to do it, with help if you want, please reply to this ticket

Kind regards

Tom

**Comment by RenaldSB** [comment] 2016-01-27 10:43
Hi,
I want to be involved in this framework.

Renald

**Comment by daniellee** [comment] 2016-01-27 16:55
I haven't been active for ages and won't be in the foreseeable future. Like Tom I am shifting away from .NET and will be focusing on golang this year. I really hope that FluentMigrator finds some new maintainers and keeps going. I know that it is a valuable tool for lots of people.

**Comment by tommarien** [comment] 2016-01-29 07:19
@RenaldSB What we are looking for is a guy/girl that would do the reviews of the pull requests and merge them in the main branch. Also releasing the software would be one of your tasks. It's commitment we are looking for ;)

**Comment by RenaldSB** [comment] 2016-01-29 10:27
@tommarien Reviews pull request is OK for a starts. Releasing software, if possible, in a second time.
Is there other contributors that are able to review pull request and releasea new version?
I will be able to merge pull request in main branch for myself or I have to wait for other contributor to validate my merge?

**Comment by jarz** [comment] 2016-01-29 19:53
I'm interested in being involved as well. My co-workers would hate to go back to hand-written SQL.

**Comment by tommarien** [comment] 2016-02-09 08:17
@jarz We want a new lead, can be co leading with me if one wants ;)

**Comment by fubar-coder** [comment] 2016-02-09 13:47
I'd be willing to help (on a co-maintainer position). I could also provide a TeamCity based build server.

**Comment by fubar-coder** [comment] 2016-02-09 14:20
I talked to the company ([DATALINE GmbH](https://www.dataline.de/)) I work for and they'd be willing to sponsor my work on FluentMigrator, which means that I'd be able to spend a few hours per week  working through the issues, reviewing pull requests and publishing new releases. However, it would be nice - due to the quite high amount of issues and pull requests - if someone else would be willing to share this position with me. The other maintainer(s) would get administrative access to the project on build server too (of course).

**Comment by zendever** [comment] 2016-03-16 05:17
@fubar-coder...do you guys still need help? I know a lot of people have thrown their hat in the ring here, and I'm also willing to help out.

**Comment by fubar-coder** [comment] 2016-03-16 05:33
Nothing seems to be decided yet. TBH: I'd be fine if someone else would become the maintainer. The only thing I wish for this project is that the project doesn't die.

**Comment by zendever** [comment] 2016-03-16 05:48
I think we're all in the same boat. We are all very busy people, I'm sure.

I'm willing to be the lead/maintainer, but full disclosure...I haven't internalized the project, so I'm pretty sure everything would be slow going, at first. Furthermore, I don't have access to some of the providers (Oracle being the big glaring deficiency), so testing may be problematic.

I guess we just need @tommarien and company to anoint someone.

**Comment by jarz** [comment] 2016-03-16 14:20
I only use FluentMigrator with Oracle, so I can cover that.

Would it make sense to create more of a plug-in architecture?
FluentMigrator.Core for "core" stuff, and FluentMigrator.SqlServer,
FluentMigrator.Oracle, etc. for the actual databases? Might make it easier
for folks to contribute to the database they primarily use.

**Comment by zendever** [comment] 2016-03-16 15:18
@jarz...I appreciate the input. Are you suggesting multiple managed projects (in GitHub)? I'm not opposed to separating the generators by provider into C# distributables if they get large enough, but I think it might get a little awkward if something changes in the Core project that needs to cascade down to the other generators. (not sure what would, but just thinking ahead)

What we could do is have multiple contributors assigned to one or more (with overlap where possible) provider who can assess the bugs and pull requests as well as perform integration testing with their assigned provider.

At this point, the generators are tiny, although I do see value in only having to pull only the targeted distributable...but I still think that'd best be managed under one hub.

What do you think?

**Comment by tommarien** [comment] 2016-03-17 10:23
Hi guys,

the most important thing atm is having more people doing pull requests ;), i will stick to the project as long as necessary

**Comment by tommarien** [comment] 2016-03-24 10:02
anyone want to help pulling and reviewing pr's ?

**Comment by fubar-coder** [comment] 2016-03-24 10:03
Yes, I'd be willing to help reviewing/merging the PRs

**Comment by tommarien** [comment] 2016-03-27 09:29
@fubar-coder Ok i will give you access can you focus on pulling pr's for 1.6.2 milestone ;)

**Comment by fubar-coder** [comment] 2016-03-27 14:43
It would be nice if there is someone else so that we can have a four-eyes review (and approval) of PRs to avoid problems that a single person could overlook easily.

**Comment by tommarien** [comment] 2016-03-27 14:54
I am still here ;), btw you have access now

Verstuurd vanaf mijn iPhone

**Comment by RenaldSB** [comment] 2016-03-27 17:45
Hi, I'm still interessed to review code and merge push request.

Renald

**Comment by RobPethick** [comment] 2016-04-05 11:00
I'm also happy to do some code review. And similarly to fubar I can spend up to half a day a week on this in company time.

**Comment by mbcrawfo** [comment] 2017-02-14 16:23
@tommarien @daniellee @fubar-coder 

What's going on?  You guys appear to have several people still trying to help answer issues and fix things with PRs, but no one is paying attention to them for about the last year.  This is an excellent tool, please don't let it die.

**Comment by reinaldocoelho** [comment] 2017-02-14 17:27
If nobody want to maintain, I would like to help and review pull requests.

**Comment by tommarien** [comment] 2017-02-15 08:02
@mbcrawfo We tried getting a new maintainer(s) by using this thread. @fubar-coder is appointed as one of them. We need more, but we need a leader ...

For myself i don't come around to doing .net anymore, but i would regret if this project would die

@fubar-coder Can you please follow up and even appoint new maintainers ;)

**Comment by fubar-coder** [comment] 2017-02-15 08:11
@tommarien Will do. I currently don't have much time due to a project for a customer, but the idea of additional maintainers is good.

**Comment by fubar-coder** [comment] 2017-02-15 08:50
@jarz @RenaldSB @zendever Are you guys still interested in becoming a maintainer of this project?

**Comment by RenaldSB** [comment] 2017-02-15 09:02
@fubar-coder Yes I'm still interested to be a maintainer but not as a leader

**Comment by fubar-coder** [comment] 2017-02-15 22:21
I plan to change the status of @RenaldSB and @reinaldocoelho to "Collaborator" as soon as I get the project access rights to do so.

**Comment by schambers** [comment] 2017-02-16 13:58
All,

I have added @RenaldSB and @reinaldocoelho as collaborators.

I can't seem to make others admins of this repo to provide access to add additional collaborators. Does anyone know how to make users admins? @fubar-coder, if i figure out how to make you an admin I'll do so. Perhaps @tommarien knows?

**Comment by tommarien** [comment] 2017-02-16 14:58
Hi Sean, 

I think you need to look in the repository settings under collaborators & teams,

Create a new team for instance maintainers and add @fubar-code (maybe you could also add me, if you trust me ;) ) to it make sure you team has admin rights

Kind regards

**Comment by reinaldocoelho** [comment] 2017-02-20 12:38
Hi guys!

I would like to undertand the rules/process to help/test/validate the Pull Requests, but I'm not sure about what I can not help.

Example:
       Can I approve Pull Request?
       Can I merge Pull Requests in new Branch to make tests?
       We apply the Git Flow process?

Sorry, but I am asking you how to get started without disturbing the current process.

Thank you

**Comment by fubar-coder** [comment] 2017-02-20 18:47
@reinaldocoelho The easy anwers first:

* Yes, you can approve PRs
* Yes, you can merge PRs
* No, we don't apply a Git Flow process (yet?)
  * TBH: I don't see the value of a Git Flow process for this project.

We need help with reviewing/merging the PRs and giving advice/support to contributors.

PS: Don't hesitate to ask when you have questions. Asking is the first step towards understanding 😁

**Comment by fubar-coder** [comment] 2017-02-27 23:57
We moved the repository to from [github.com/schambers/fluentmigrator](https://github.com/schambers/fluentmigrator/) to the new [fluentmigrator](https://github.com/fluentmigrator) organization ([github.com/fluentmigrator/fluentmigrator](https://github.com/fluentmigrator/fluentmigrator/)). This allows us to have more than one administrator.

@tommarien @schambers The transfer was successful. What needs to be done for the build server? I guess that the repository URL has to be changed? Or should I try to setup a new build server?

@reinaldocoelho @RenaldSB I'll give you write access.

**Comment by escarls** [comment] 2017-02-28 07:09
I can help with the build servers if needed.
I seem to be working on that anyway :)

**Comment by tommarien** [comment] 2017-02-28 07:26
@fubar-coder Yep i think it's just a matter of the changing the repo

**Comment by fubar-coder** [comment] 2017-02-28 08:30
@tommarien Who can do this?
@escarls The build server situation is a bit ugly, because we must have at a build server running Windows when we want to target .NET Core due to the issue dotnet/sdk#335 being resolved for the tooling version 1.1.

**Comment by tommarien** [comment] 2017-02-28 08:41
@fubar-coder i can or you, if you create an account and give me the username ;)

**Comment by escarls** [comment] 2017-02-28 09:02
@fubar-coder Travis-ci can build for dotnet core if configured correctly (on Linux).
And from the looks of the logs, the TeamCity server is running Windows.

**Comment by fubar-coder** [comment] 2017-02-28 09:28
@tommarien I don't have access to the currently used build servers (neither Travis-CI nor TeamCity), sorry 😟 . Do you know who has?

@escarls The problem isn't the .NET core build itself. The problem is, that we cannot create .NET Framework 4.5 compatible assemblies on a Linux build server, because the .NET tooling 1.0 cannot find the mono GAC assemblies it needs to build a .NET Framework 4.5 assembly.

**Comment by tommarien** [comment] 2017-02-28 09:47
@fubar-coder I made the necessary changes for travis and updated the build badge in the readme, for codebetter i have to find the mail from jetbrains because they took over the buildserver

**Comment by tommarien** [comment] 2017-02-28 10:16
@fubar-coder if you create an account on https://teamcity.jetbrains.com and pass me the username i can make you admin too ;). But i think i fixed what was necessary

**Comment by escarls** [comment] 2017-02-28 10:48
@fubar-coder that is true with the current .travis.yml.
The current .travis.yml is building with a very old mono version.
I have been able to make it compile with the latest mono version and that should be able to generate 4.5 assemblies.
I'll try in my fork as a poc :)

**Comment by fubar-coder** [comment] 2017-02-28 10:50
@escarls Yes, that would be nice. But please try it with .NET Core RC4 tooling (new style csproj, msbuild based), because the preview2 tooling (project.json) is deprecated.

**Comment by marcrocny** [comment] 2017-03-08 22:36
FYI, sub-head on the landing page still references schambers/fluentmigrator

**Comment by fubar-coder** [comment] 2017-03-13 18:21
@RenaldSB You already have write access. Are you still interested in this project? @reinaldocoelho Might need help too 😉 

I created a [gitter room](https://gitter.im/FluentMigrator/fluentmigrator) where we can easily discuss things, like:

* Questions about the code review for pull requests
* The future versions and features
* ... etc

**Comment by RenaldSB** [comment] 2017-03-15 13:54
@fubar-coder Yes I'm still interested.
Since two weeks, I don't have time to check the project.
I will have times in 2 weeks

**Comment by fubar-coder** [comment] 2018-03-31 21:51
I'm currently in the process to release a version 2.0.0 with .NET Standard 2.0 support, but we still need a maintainer that I can share the work with.

**Comment by ManfredLange** [comment] 2018-05-11 02:37
I don't have large amounts of time but subject to what needs to be done I may be able to help out. We are using this framework in several projects, so we would love to see it's maintenance being continued.

**Comment by fubar-coder** [comment] 2018-05-11 07:15
I'm thankful for help. What are the parts that you're interested in? I'm currently in the progress of documenting the fluent API and replacing the hand-written interfaces with automatically generated ones.

There are some parts where incremental improvement would help:

- Documentation
    - xmldoc
    - Articles (https://github.com/fluentmigrator/documentation)
- Improvement of DB support
    - e.g. issue #812 
    - Extensions for DB-specific features
- Improved error messages (e.g. issue #385)

Big changes would be tasks like:

- Support for idempotent migrations
    - Deprecation of the query API
    - Differentiating between delete and drop (deprecating large parts of the `Delete` part)
- Fluent API generator

**Comment by ManfredLange** [comment] 2018-05-13 20:13
I don't really have preferences. All three areas where incremental would help are fine by me. What is your preference given you have had many more interactions with the users of this library?

**Comment by fubar-coder** [comment] 2018-05-14 08:26
@ManfredLange One pain point is always the documentation. I already added lots of xmldoc comments, and tried my best for the [documentation](https://fluentmigrator.github.io) page, but it's still not enough.

**Comment by ManfredLange** [comment] 2018-05-14 20:49
Sounds good to me. Let me have a look at [documentation repo](https://github.com/fluentmigrator/documentation).

Do you already have some form of communication within the team? If you wish you can drop me a note  [here](https://www.urnextgig.com/Home/ContactUs) to establish email contact.

**Closed** 2020-04-04 22:07 UTC
Labels: discussion
