### ISSUE TITLE
Execute and Delete does not exist in the current context

### ISSUE THREAD

**Issue by Rinfra90** [fluentmigrator/fluentmigrator#1665] opened 2023-06-26 07:28 UTC
I'm using Serenity Framework who auto-import the FluentMigrator package.
When I try to execute a personalized query, I receive an error on Execute.Sql

The error is: `Execut does not exist in the current context`

This is my code

```
using FluentMigrator;

namespace MyNameSpace.Migrations.DefaultDB
{
    [Migration(20230623_172000)]
    public class DefaultDB_20230623_172000_Insert : AutoReversingMigration
    {
        public override void Up()
        {
            Execute.Sql(
              @"My query");
        }
    }
}
```

I also have the same error using `Delete`

**Comment by Rinfra90** [comment] 2023-06-28 09:24
Solved

**Comment by Rinfra90** [comment] 2023-06-28 09:25
Solved

**Comment by jzabroski** [comment] 2023-07-14 15:21
Duplicate of #1666

**Closed by jzabroski** 2023-07-14 15:21 UTC
