### ISSUE TITLE
Oracle Migration with Alter Table Add Column

### ISSUE THREAD

**Issue by Noobishness** [fluentmigrator/fluentmigrator#791] opened 2017-03-28 11:43 UTC
Hi together,

currently the Oracle implementation does not consider the Schema passed to the CreateColumnExpression. In my opinion this should behave similar to the MSSQL Version which includes the Schema Name in the alter table query string

Best regards

**Comment by fubar-coder** [comment] 2018-04-13 12:26
The schema handling of ORACLE (and other databses) was streamlined and this problem should be fixed in 2.0.0. Please leave a comment if the issue is still there after the 2.0 release.

**Closed by fubar-coder** 2018-04-13 12:26 UTC
Labels: db:oracle
