### ISSUE TITLE
SQLite Error 5: 'database is locked'.

### ISSUE THREAD

**Issue by suatsuphi** [fluentmigrator/fluentmigrator#1644] opened 2023-01-05 20:53 UTC
Hi, I'm trying to add the SqLiteNopDataProvider for nopcommerce. there is a topic in [forum](https://www.nopcommerce.com/tr/boards/topic/95827/sqlite-error-5-database-is-locked)
I get this error when migration runs: SQLite Error 5: 'database is locked'. I cant see detail...
could it be a bug? 

FluentMigrator.Runner.MigrationRunner: Information: LocalizationMigration migrating
FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor: Information: Beginning Transaction
The thread 0x5844 has exited with code 0 (0x0).
The thread 0x5e1c has exited with code 0 (0x0).
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
An exception of type 'Microsoft.Data.Sqlite.SqliteException' occurred in Microsoft.Data.Sqlite.dll but was not handled in user code
SQLite Error 5: 'database is locked'.

**Comment by jzabroski** [comment] 2023-02-04 16:37
Sqlite is single threaded. Are you using multiple threads?  It is super dangerous if you are.  FluentMigrator is single threaded so I think the problem is on your end. Closing for now.

**Closed by jzabroski** 2023-02-04 16:37 UTC

**Comment by jzabroski** [comment] 2023-02-04 17:28
Actually, let me redact my previous reply and elaborate what I mean:

https://www.sqlite.org/threadsafe.html

If you read this, you can configure SQLite to run in multi-threaded mode.  When you do, the documentation implies connection pooling is unsafe: 

> Multi-thread. In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads.

While it is possible a SQLite client allows / manages connection pooling in a safe manner consistent with all 3 threading modes and therefore connection pooling would be safe independent of threadsafety mode, **I do not see any tests that prove it**. For an idea of database integration tests, refer to the Jepsen test suite that proved several thread safety problems with MongoDB.

**Comment by suatsuphi** [comment] 2023-02-04 17:31
thank you.

**Comment by jzabroski** [comment] 2023-02-04 17:34
The other possibility, Googling around a bit, is that it may be problematic to modify the database in certain ways while other threads are connected: https://www.arysontechnologies.com/blog/fix-sqlite-error-database-locked/

This blog post suggests the only safe way to modify the database schema of a Sqlite database is to take a copy of the original.  - Honestly, that does not make a lot of sense to me for many reasons. One obvious reason is that you will lose some writes while the migration takes place, if there are any other active connections.

To be honest, this gets into a broad problem I see with projects that use SQLite. I've used backup software that maintains is database of what has been backed up in a sqlite db. They often don't read the manual and interface sqlite with entity framework without reading the entity framework manual and/or thinking through thread safety logic. They then spawn multiple DbContext objects from Entity Framework and just assume everything will work, and it does not.

**Comment by jzabroski** [comment] 2023-02-04 17:37
@suatsuphi If you can run your migrations in a non-concurrent manner and avoid multiple connections and still see this issue, feel free to re-open. Obviously its painful to hoist your sample code out of NopCommerce but it may actually teach you a lot about how the libraries you depend upon actually work. Becoming an expert, while not always fun, can be redemptive for the time lost dealing with the madness.

**Comment by suatsuphi** [comment] 2023-02-04 17:38
thanks :)

**Comment by suatsuphi** [comment] 2023-02-09 11:35
@jzabroski could you give me an example about multi thread. I cant find any example about how to set. 
journal_mode = wall is not working. I cant set THREADSAFE=2 cold you give an example. 


```
var connection = new SqliteConnection(connectionString)
 var cmd = connection.CreateCommand();
            cmd.CommandText = "PRAGMA journal_mode=WAL;";
            if (connection.State == ConnectionState.Closed)
                connection.Open();
            cmd.ExecuteNonQuery();
```
 
PRAGMA  THREADSAFE=2 is not working. how to set this threadsafe=2 ? 

could you override this sqlite connection on fluentmigrator with ? 

If the connection is not in multi-thread mode during the migration, the migration crashes.

**Comment by jzabroski** [comment] 2023-02-09 19:46
I found this blog post: https://echo17.proboards.com/post/751/thread - read it carefully.  You cant use pragma.

**Comment by suatsuphi** [comment] 2023-02-09 21:43
I cant figured out. I am a beginner. Is there any way about multithread ? or no way for sqlite? is multi thread safe ? I confused... migration is not working for sqlite on nopcommerce

**Comment by jzabroski** [comment] 2023-02-09 21:51
OK.  I did not know you are a beginner.  Let's try to simplify things to a beginner level.  Did you try disabling connection pooling?  The FluentMigrator FAQ mentions that approach [for a different problem, which is connections not getting cleaned up at the end of a FluentMigrator migrate up sequence.](https://fluentmigrator.github.io/articles/faq.html#sqlite-specific-topics)

**Comment by suatsuphi** [comment] 2023-02-11 19:40
Hi, As far as I understand, it is necessary to close the connection. I tried it. I wanna share code. I can not figured this out. 
I made DbConnection static - to be able to close the connection. If connection is called for the second time, I close the existing connection. I can see it with breakpoint that it is working but again same error. if you have a time, do you have a chance to review the nopcommerce repository? I wonder why it isn't working.


            if (_connection != null)
            {
                _connection.Dispose();
                _connection.Close();
                _connection = null;
            }




```

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlServerCe;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider;
using LinqToDB.DataProvider.SQLite;
using LinqToDB.SqlQuery;
using Microsoft.Data.Sqlite;
using Newtonsoft.Json.Linq;
using Nop.Core;
using Nop.Core.Infrastructure;
using Nop.Data.Migrations;
using StackExchange.Profiling.Data;
using StackExchange.Profiling;
using static LinqToDB.DataProvider.DB2.DB2ProviderAdapter;
using Nop.Data.DataProviders.Interceptors;
using System.Linq.Expressions;
using Nop.Data.Mapping;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Mapping;

 
namespace Nop.Data.DataProviders
{

    /// <summary>
    /// Represents the SQLite data provider
    /// </summary>
    public partial class SqLiteNopDataProvider : BaseDataProvider, INopDataProvider
    {
        #region Consts
        //it's quite fast hash (to cheaply distinguish between objects)
        private const string HASH_ALGORITHM = "SHA1";
        private static DataConnection _dataContext;

        public static DbConnection _connection;
        #endregion

        #region Methods
        protected static string GetCurrentConnectionString()
        {
            return "Data Source=App_Data\\\\Database.db;Pooling=false;Cache=shared;Mode=ReadWriteCreate;";
        }

        public void CreateDatabase(string collation, int triesToConnect = 10)
        {
            ExecuteNonQueryAsync("PRAGMA foreign_keys = true;PRAGMA journal_mode=WAL;PRAGMA writable_schema=1;").Wait();
        }
        /// <summary>
        /// Creates a connection to a database
        /// </summary>
        /// <param name="connectionString">Connection string</param>
        /// <returns>Connection to a database</returns>
        protected override DbConnection CreateDbConnection(string connectionString = null)
        {
            if (_connection != null)
            {
                _connection.Dispose();
                _connection.Close();
                _connection = null;
            }

            _connection  = GetInternalDbConnection(!string.IsNullOrEmpty(connectionString) ? connectionString : GetCurrentConnectionString());
            
            return _connection ;
        }
        protected override DataConnection CreateDataConnection()
        {
            return CreateDataConnection(LinqToDbDataProvider);
        }

        protected override DataConnection CreateDataConnection(IDataProvider dataProvider)
        {
            if (dataProvider is null)
                throw new ArgumentNullException(nameof(dataProvider));

            _connection = CreateDbConnection();
            var dataConnection = new DataConnection(dataProvider, _connection, GetMappingSchema())
            {
                CommandTimeout = DataSettingsManager.GetSqlCommandTimeout()
            };

            if (MiniProfillerEnabled)
            {
                dataConnection.AddInterceptor(UnwrapProfilerInterceptor.Instance);
            }
            
            return dataConnection;
        }

        /// Gets a connection to the database for a current data provider
        /// </summary>
        /// <param name="connectionString">Connection string</param>
        /// <returns>Connection to a database</returns>
        protected override DbConnection GetInternalDbConnection(string connectionString)
        {
            if (string.IsNullOrEmpty(connectionString))
                throw new ArgumentNullException(nameof(connectionString));

             _connection = new SqliteConnection(string.IsNullOrEmpty(connectionString)
                ? DataSettingsManager.LoadSettings().ConnectionString : connectionString);

            return _connection;
        }

        /// <summary>
        /// Initialize database
        /// </summary>
        public override void InitializeDatabase()
        {
            var migrationManager = EngineContext.Current.Resolve<IMigrationManager>();
            var targetAssembly = typeof(NopDbStartup).Assembly;
            migrationManager.ApplyUpMigrations(targetAssembly);
            //mark update migrations as applied
            migrationManager.ApplyUpMigrations(targetAssembly, MigrationProcessType.Update, true);
        }

        /// <summary>
        /// Gets the name of a foreign key
        /// </summary>
        /// <param name="foreignTable">Foreign key table</param>
        /// <param name="foreignColumn">Foreign key column name</param>
        /// <param name="primaryTable">Primary table</param>
        /// <param name="primaryColumn">Primary key column name</param>
        /// <returns>Name of a foreign key</returns>
        public string CreateForeignKeyName(string foreignTable, string foreignColumn, string primaryTable, string primaryColumn)
        {
            return "FK_" + HashHelper.CreateHash(Encoding.UTF8.GetBytes($"{foreignTable}_{foreignColumn}_{primaryTable}_{primaryColumn}"), HASH_ALGORITHM);
        }

        /// <summary>
        /// Gets the name of an index
        /// </summary>
        /// <param name="targetTable">Target table name</param>
        /// <param name="targetColumn">Target column name</param>
        /// <returns>Name of an index</returns>
        public string GetIndexName(string targetTable, string targetColumn)
        {
            return "IX_" + HashHelper.CreateHash(Encoding.UTF8.GetBytes($"{targetTable}_{targetColumn}"), HASH_ALGORITHM);
        }

        /// <summary>
        /// Get the current identity value
        /// </summary>
        /// <typeparam name="TEntity">Entity</typeparam>
        /// <returns>Integer identity; null if cannot get the result</returns>
        public Task<int?> GetTableIdentAsync<TEntity>() where TEntity : BaseEntity
        {
            var tableName = DataContext.GetTable<TEntity>().TableName;

            var result = DataContext.Query<int?>($"select seq from sqlite_sequence where name = \"{tableName}\";")
                .FirstOrDefault();

            return Task.FromResult<int?>(result ?? 1);
        }

        public Task<bool> DatabaseExistsAsync()
        {
            return Task.FromResult(DatabaseExists());
        }

        /// <summary>
        /// Checks if the specified database exists, returns true if database exists
        /// </summary>
        /// <returns>Returns true if the database exists.</returns>
        public bool DatabaseExists()
        {
            return true;
        }

        /// <summary>
        /// Creates a backup of the database
        /// </summary>
        public virtual Task BackupDatabaseAsync(string fileName)
        {
            throw new DataException("This database provider does not support backup");
        }

        /// <summary>
        /// Restores the database from a backup
        /// </summary>
        /// <param name="backupFileName">The name of the backup file</param>
        public virtual Task RestoreDatabaseAsync(string backupFileName)
        {
            throw new DataException("This database provider does not support backup");
        }

        /// <summary>
        /// Re-index database tables
        /// </summary>
        public Task ReIndexTablesAsync()
        {
            DataContext.Execute("VACUUM;");
            return Task.CompletedTask;
        }

        /// <summary>
        /// Build the connection string
        /// </summary>
        /// <param name="nopConnectionString">Connection string info</param>
        /// <returns>Connection string</returns>
        public string BuildConnectionString(INopConnectionStringInfo nopConnectionString)
        {
            if (nopConnectionString is null)
                throw new ArgumentNullException(nameof(nopConnectionString));

            if (nopConnectionString.IntegratedSecurity)
                throw new NopException("Data provider supports connection only with password");

            var builder = new SqliteConnectionStringBuilder
            {
                DataSource = CommonHelper.DefaultFileProvider.MapPath($"~/App_Data/{nopConnectionString.DatabaseName}.db"),
                Password = nopConnectionString.Password,
                Mode = SqliteOpenMode.ReadWriteCreate,
                Cache = SqliteCacheMode.Shared,
                Pooling = false,
            };

            return builder.ConnectionString;
        }

        /// <summary>
        /// Set table identity (is supported)
        /// </summary>
        /// <typeparam name="TEntity">Entity</typeparam>
        /// <param name="ident">Identity value</param>
        public Task SetTableIdentAsync<TEntity>(int ident) where TEntity : BaseEntity
        {
            var tableName = DataContext.GetTable<TEntity>().TableName;
            DataContext.Execute($"update sqlite_sequence set seq = {ident} where name = \"{tableName}\";");

            return Task.CompletedTask;
        }

        /// <summary>
        /// Creates database command instance using provided command text and parameters.
        /// </summary>
        /// <param name="sql">Command text</param>
        /// <param name="dataParameters">Command parameters</param>
        protected override CommandInfo CreateDbCommand(string sql, DataParameter[] dataParameters)
        {
            if (dataParameters is null)
                throw new ArgumentNullException(nameof(dataParameters));

            return new CommandInfo(DataContext, sql, dataParameters);
        }

        #endregion

        #region Properties

        public DataConnection DataContext
        {
            get
            {

                return _dataContext ??= CreateDataConnection();

            }
            set
            {
                _dataContext = value;
            }
        }

        // => _dataContext ??= CreateDataConnection();

        /// <summary>
        /// Linq2Db data provider
        /// </summary>
        protected override IDataProvider LinqToDbDataProvider { get; } = SQLiteTools.GetDataProvider(ProviderName.SQLiteMS);

        /// <summary>
        /// Gets allowed a limit input value of the data for hashing functions, returns 0 if not limited
        /// </summary>
        public int SupportedLengthOfBinaryHash { get; } = 0;

        /// <summary>
        /// Gets a value indicating whether this data provider supports backup
        /// </summary>
        public bool BackupSupported { get; } = false;

        #endregion
    }

}

```

**Comment by jzabroski** [comment] 2023-02-12 12:27
Sorry, I can't review code of other massive projects.

**Comment by suatsuphi** [comment] 2023-02-12 15:04
I see... 

I tried to close connection before for each connection. something is wrong I cant detail but I guess this is about fluentmigrator. when I changed structure of migration, it is working and no problem. I mean if I call it same time occur deadlock. but this error is just for SQLITE 

```

                //update nopCommerce core and db
                var migrationManager = engine.Resolve<IMigrationManager>();
                var assembly = Assembly.GetAssembly(typeof(ApplicationBuilderExtensions));
                migrationManager.ApplyUpMigrations(assembly, MigrationProcessType.Update);
                assembly = Assembly.GetAssembly(typeof(IMigrationManager));
                migrationManager.ApplyUpMigrations(assembly, MigrationProcessType.Update);

```

I cant control connection with DataConnection class that it is in fluentmigrator. I mean I can't close the connection

```

        private static DataConnection _dataContext;
        public DataConnection DataContext => _dataContext ??= CreateDataConnection(LinqToDbDataProvider);

        protected override DataConnection CreateDataConnection(IDataProvider dataProvider)
        {
            if (dataProvider is null)
                throw new ArgumentNullException(nameof(dataProvider));
             
            if (_dataContext != null)
            { 
                _dataContext.Dispose();
                _dataContext.Close();
                _dataContext = null;

            }
            var dataConnection = new DataConnection(dataProvider, CreateDbConnection(), GetMappingSchema())
            {
                CommandTimeout = DataSettingsManager.GetSqlCommandTimeout()
            };

            if (MiniProfillerEnabled)
            {
                DataContext.AddInterceptor(UnwrapProfilerInterceptor.Instance);
            }
            
            return dataConnection;
        }
```

**Comment by jzabroski** [comment] 2023-02-12 16:13
We don't have a class called DataConnection in this code base, so it's not FluentMigrator. Maybe you should ask NopCommerce. I don't understand why they wrapped FluentMigrator the way they did (maybe it's a good idea, I don't know).

**Comment by suatsuphi** [comment] 2023-02-12 22:01
This is about [linq2db](https://github.com/linq2db/linq2db) thank you again...

**Comment by jzabroski** [comment] 2023-02-13 15:52
Sorry, did you see my suggestion to ask NopCommerce?  Seems like they are using a bunch of different libraries.  `Nop.Data.Migrations` is not a nuget package on nuget.org, so I have zero interest in continuing this discussion.  If you are using a proprietary system that isn't open source, you need to be asking them for support, not me.
