### ISSUE TITLE
Execute.Sql() cannot execute stored procedure with Oracle runner

### ISSUE THREAD

**Issue by kriewall** [fluentmigrator/fluentmigrator#1157] opened 2020-01-23 00:35 UTC
##### Describe the bug
* Not able to execute stored procedure in Oracle using Fluent Migrator

##### Steps to reproduce 
A standalone project replicating the issue can be found [here](https://1drv.ms/u/s!AsvM6Pyke4A6hm56GF31XBHcjSYt?e=tKNmZz).  
* Load the package
* Update the connection string in MigrationRun.cs 
* Run MigrateRun_Up.bat from the command prompt.

##### Expected behavior
* Stored procedure should be executable from within Fluent Migrator.

##### Screenshots
![image](https://user-images.githubusercontent.com/38048622/72946500-fe761780-3d33-11ea-9f4f-949dd6b6f92a.png)

##### Environment
      * Oracle.ManagedDataAccess v18.6.0
      * FluentMigrator v3.2.1
     * FluentMigrator.Runner.Oracle v3.2.1
      * Windows 10
      * Oracle 11.2.0.4

##### Additional context
See M0001_CreateMemberTable for details.  Stored procedure can be run successfully using `EXEC CREATE_INDEX` without Fluent Migrator, but for some reason doesn't work when it is wrapped in an `Execute.Sql()` method.

**Comment by jzabroski** [comment] 2020-01-23 20:34
I don't think this is a FM issue.  I don't have Oracle available, but I believe the issue is you are trying to execute the stored procedure in the same transaction you are creating it.  Please move the exec statement into its own migration and see if that works.

**Comment by kriewall** [comment] 2020-01-24 01:14
Hi @jzabroski - tried your suggestion, but it looks like the issue persists:

![image](https://user-images.githubusercontent.com/38048622/73037402-c2aa8300-3e03-11ea-973f-3e55a975701f.png)

Anything else we could try?

**Comment by jzabroski** [comment] 2020-01-24 16:30
@kriewall Is it possible in Migrate_Up.bat you are using the default transaction per session mode, and that is causing issues?  In reading up on this, I found this thread helpful: https://stackoverflow.com/questions/6973003/oracle-dbms-utility-exec-ddl-statement-vs-execute-immediate

I last did Oracle in college in 2004 and got an A+, but that's a long time ago.

I signed up for livesql.oracle.com account just now.  Will look more this weekend.

**Comment by kriewall** [comment] 2020-01-31 21:50
Hey @jzabroski Sorry for the slow response.  We tried the non-default transaction mode ("None") but no difference in behavior.  Did you find anything of interest on the Oracle forums?

Here's hoping you can channel that inner valedictorian to a solution for us.  My feeble brain is stumped!

**Comment by jzabroski** [comment] 2020-02-10 19:05
@kriewall Thanks for your patience!! Just returned from vacation, and appreciated the humor as one of the first things I read.  I started moving it into LiveSQL now: https://livesql.oracle.com/apex/livesql/s/jnjhwpd7wn7pbx6opcezq5ldg

**Comment by jzabroski** [comment] 2020-02-10 22:14
@kriewall a bit hacky, but i updated your `MigrationRun.cs` file to be this:

```c#
using FluentMigrator.Runner;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DatabaseMigration.Migrations;
using FluentMigrator.Runner.Initialization;
using FluentMigrator.Runner.Processors;

namespace DatabaseMigration
{
    public class MigrationRun
    {
        public  static void runMigrations()
        {
            Console.WriteLine("Test it ");
            
        
            var serviceProvider = CreateServices();

            // Put the database update into a scope to ensure
            // that all resources will be disposed.
            using (var scope = serviceProvider.CreateScope())
            {
                UpdateDatabase(scope.ServiceProvider);
            }
             Console.WriteLine("Test it DONE");
            Console.ReadLine();
        }
         private static IServiceProvider CreateServices()
        {
            return new ServiceCollection()
                // Add common FluentMigrator services
                .AddFluentMigratorCore()
                .AddOptions()
                .Configure<RunnerOptions>(s =>
                {
                    s.NoConnection = true;
                })
                .Configure<ProcessorOptions>(
                    opt =>
                    {
                        opt.ConnectionString = null as string;
                        opt.PreviewOnly = true;
                        opt.ProviderSwitches = "OracleManaged";
                        opt.StripComments = true;
                        opt.Timeout = (TimeSpan?)null;
                    })
                .ConfigureRunner(rb => rb
                    // Add SQLite support to FluentMigrator
                    .AddOracle()
                    // Set the connection string
                    .WithGlobalConnectionString(null as string)
                    // Define the assembly containing the migrations
                    .ScanIn(typeof(M0001_CreateMemberTable).Assembly).For.Migrations())
                // Enable logging to console in the FluentMigrator way
                .AddLogging(lb => lb.AddFluentMigratorConsole())
                .Configure<FluentMigratorLoggerOptions>(
                    opt =>
                    {
                        opt.ShowElapsedTime = true;
                        opt.ShowSql = true;
                    })
                // Build the service provider
                .BuildServiceProvider(false);
        }

        private static void UpdateDatabase(IServiceProvider serviceProvider)
        {
            // Instantiate the runner
            var runner = serviceProvider.GetRequiredService<IMigrationRunner>();
            
            // Execute the migrations
            runner.MigrateUp();
        }
    }
}
```

And was able to run it to get the following sql outputs:

```sql
CREATE TABLE Address (AddressId NUMBER(10,0) NOT NULL, Street NVARCHAR2(50) NOT NULL, AddressLine1 NVARCHAR2(40) NOT NULL, AddressLine2 NVARCHAR2(40) NOT NULL, CONSTRAINT PK_Address PRIMARY KEY (AddressId))
```
```sql
Insert into Address values(1,'tt', 'line1', 'line2')
```
```sql
CREATE TABLE Member (MemberId NUMBER(10,0) NOT NULL, Name NVARCHAR2(50) NOT NULL, AddressId NUMBER(10,0) NOT NULL, MobileNo NVARCHAR2(50) NOT NULL, CONSTRAINT PK_Member PRIMARY KEY (MemberId))
```
```sql
ALTER TABLE Member ADD CONSTRAINT FK_Member_Address FOREIGN KEY (AddressId) REFERENCES Address (AddressId)
```
```sql
CREATE OR REPLACE PROCEDURE CREATE_Index
AS
BEGIN
DBMS_UTILITY.EXEC_DDL_STATEMENT('Create Index Member_AddrId on Member(AddressId)');

END CREATE_Index;
```
```sql
Exec CREATE_INDEX
```
```sql
INSERT ALL INTO VersionInfo (Version, AppliedOn, Description) VALUES (1, to_date('2020-02-10 22:11:03', 'yyyy-mm-dd hh24:mi:ss'), 'M0001_CreateMemberTable') SELECT 1 FROM DUAL
```

I will update the linked LiveSQL in my previous comments with this output.

**Comment by jzabroski** [comment] 2020-02-10 22:23
Updated LiveSQL - it indeed seems to work.  I'm a little confused as to why this throws an error.

As a quick thought - could you try the part of code where I explicitly configure your In Process Runner to use the new OracleManaged client?  I wonder if you're using the Oracle client.  In your screenshot provided, it's not logging which client you're configured for, which might be an oversight, but Oracle is really one of the few database engines where there are multiple clients.

**Comment by jzabroski** [comment] 2020-02-10 22:34
One other suggestion:

Can you try changing this line:

```c#
//The following Statement Fails during Migration Run.
            Execute.Sql("Exec CREATE_INDEX");
```

to this:

```
//The following Statement Fails during Migration Run.
            Execute.Sql("CREATE_INDEX");
```

My reasoning is that I think this gets passed directly to the underlying provider.

The other option might be to try `Execute.WithConnection` or `Create.Index`

**Comment by jzabroski** [comment] 2020-02-10 23:29
@kriewall One last thing.  Avi Miller, Product Owner of Oracle Database, suggested I may be able to use the OracleDatabase SingleInstance docker image using Oracle Express Edition.  I was not aware of this possibility.  However, to temper expectations, I recall in college installing Oracle / standing it up required passing a test and that was half the battle of becoming Oracle Certified :)  So, I might not get to it right away.

**Comment by kriewall** [comment] 2020-02-11 21:06
@jzabroski Thanks for getting back with me - we'll try out some of your content above and try again to get it to work on our end.  We too have a lot going on at the moment without even becoming Oracle Certified, so we might be a little slow to get back as well.  Race ya!  :)

**Comment by kriewall** [comment] 2020-02-16 12:59
@jzabroski We tried out your recommendations above but we still get the same result.  However, at this point I think we have a workaround - we created a standalone executable for the migrator that runs the stored procedure directly via an OracleConnection.  Up to you if you want to keep this item open or not - we're happy to try out any recommendations you throw our way if you want to keep plugging on it.

**Comment by jzabroski** [comment] 2020-02-16 17:49
Interesting.  So Execute.WithConnection and casting the connection to an OracleConnection and passing an OracleCommand that connection didn't do the trick?  That's odd.  I'd like to solve these - I have a roadmap to improve FluentMigrator where eventually I'd like to use FluentMigrator to benchmark various databases, and write a whitepaper about it (everyone talks about doing "DbOps in DevOps" but very few seem to use tools to facilitate it).  Not being able to create indexes is a major roadblock to doing benchmarks.

@PhenX - pinging you to see if you've run into this problem, as you're the last contributor to the FluentMigrator Oracle subsystem.  If you don't have time to reply, I totally understand :)

**Comment by PhenX** [comment] 2020-02-17 09:38
@jzabroski no, sorry, I never had to execute a stored procedure from a migration. Have you tried this syntax ? https://stackoverflow.com/questions/1854427/how-to-execute-an-oracle-stored-procedure
```
begin 
    temp_proc;
end;
```

**Comment by jzabroski** [comment] 2020-02-17 15:52
@PhenX That makes a ton of sense.  Thank you.
@kriewall  Can you give that a shot?  The gist of it is BEGIN/END block encapsulates PLSQL and you cannot call a stored procedure in the SQL grammar, only the PLSQL grammar.  If this works, I'll add it to the FAQ.

**Comment by kriewall** [comment] 2020-02-17 22:01
@jzabroski It works!  Sorry we didn't try this in the first place.  FAQ away - thanks for the great support on this!  :)

**Comment by jzabroski** [comment] 2020-02-17 22:10
@PhenX you rock!

**Closed by jzabroski** 2020-02-17 22:10 UTC

**Comment by jzabroski** [comment] 2020-02-17 22:18
Fixed in  https://github.com/fluentmigrator/documentation/commit/c5739d810f7d15f948ae5357292e1fc71d732f2b - needs refreshing
