### ISSUE TITLE
It would be great if we could dynamically execute a migration based on a schema defined at runtime.

### ISSUE THREAD

**Issue by aderderian** [fluentmigrator/fluentmigrator#1393] opened 2020-12-14 01:16 UTC
For example,  user uploads and excel file and you want to parse the data sheets and columns into a database. Sheets being tables and columns in the sheet being columns in that table. How could we build the class dynamically and execute a migration on it? Should we write the class file out, dynamically compile it, then run the migration on it? Or use reflection on an existing class and pass in parameters for the different schemas?

Anyone ever tried something like this?

**Comment by jzabroski** [comment] 2020-12-14 13:49
I think you're overthinking the task. 

1. Use Aspose.Cells and write out the individual tabs into csv files (strip out all formatting from Excel)
2. Make sure you archive the CSVs so that you can revisit in case of any bugs
3. Use CsvHelper to parse the files
4. For each parsed row, validate the data before inserting it
5. Call insert based on the table name. 

I don't think you need to use reflection. Just load the appropriate csv Parser that returns a closed generic TTable where the TTable is the concrete object to insert.

Let me know if you have any questions.

**Comment by aderderian** [comment] 2020-12-14 15:26
@jzabroski so you're saying build a generic class like TMigration? And then just use that each time I want to create a new table? The number of tables (sheets) and columns (columns in  sheet), and format is not known before runtime. So theoretically someone could upload any excel and we would build the tables dynamically using FluentMigrator. A Schema would be persisted for versioning into the database based on file name in case the formats/tables/etc changed down the line.

**Comment by jzabroski** [comment] 2020-12-14 21:10
Did you try using an `IExpandoObject`?  Not sure if FluentMigrator Insert supports it (I doubt it). #981 was the last time someone requested something similar.  In theory, it's do-able.  I never did it because there were bugs in .NET Framework with handling DLR types, that I was never able to find the root cause of (although I did [submit a full repro privately](https://github.com/dotnet/runtime/issues/44083) to Charles Stoner who is the lead on `System.Dynamic.Runtime`).  It does seem like the DLR on .NET 5 is much more stable than .NET Framework, so it might not be a bad idea to support `IExpandoObject` and/or `IDictionary<string, object>`.

I'd give using the dynamic keyword a shot, and see if it works.  I haven't tried it.  I'm not sure if it will work.  But there is a good chance it will "lie" to the FluentMigrator reflection calls in such a way that it "just works".

**Comment by jzabroski** [comment] 2020-12-14 21:13
Here is an example of what I mean about possibly tricking the system: https://stackoverflow.com/a/36558165/1040437

Obviously, it would be better of this was covered by tests.  But, if you need a solution, this might give you some inspiration.  You can also submit a PR to address #981

**Comment by jzabroski** [comment] 2020-12-14 21:17
Closing as duplicate of #981

**Closed by jzabroski** 2020-12-14 21:17 UTC
