### ISSUE TITLE
How to create partitioned table?

### ISSUE THREAD

**Issue by hakancunier** [fluentmigrator/fluentmigrator#1569] opened 2022-02-23 20:02 UTC
Is there a way to create a table with partitions in postgresql. I mean;

CREATE TABLE customers (id INTEGER, status TEXT, arr NUMERIC) **PARTITION BY LIST(status);**

**Comment by jzabroski** [comment] 2022-02-24 03:57
This is a duplicate of #967 which is not yet supported.

**Closed by jzabroski** 2022-02-24 03:57 UTC
