### ISSUE TITLE
Comments in stored procedures and functions are missing

### ISSUE THREAD

**Issue by theexar** [fluentmigrator/fluentmigrator#956] opened 2018-11-17 19:37 UTC
Assembly target framework: .NET Standard 2.0
FluentMigrator Nuget package version: 3.1.3
FluentMigrator runner: fluentmigrator.dotnet.cli 3.1.3
Database server: MSSQL Server 14.0 (EXPRESS)
SQL Management Studio 17.9

A repository with a working example can be found here: https://github.com/theexar/FluentMigrator-omitted-comments-example

The example project consists of a single migration that executes 3 embedded scripts to create a view, a stored procedure and a function. Each declaration has comments in it. 

After applying the migration with the 'dotnet-fm migrate' I go to SQL Management Studio. Using the 'Script -> Create as' option I get a script that contains the object's declaration. The view is exported as it is declared inside the embedded script. However, the same is not true for the exported declaration of the function and the stored procedure. The comments that are present in the Fluent Migrator model are missing on the server.

**Alternative approach** 
The --output option of the dotnet-fm tool exports the SQL script that is executed against the database. This exported script properly contains all comments. Executing it manually on the server produces a desired state: scripting the procedure and the function exports a declaration that contains all the comments just like it should.

**Summary**: using the dotnet-fm tool to add a stored procedure or a function to the database incorrectly ommits the comments inside the procedure's (or function's) declaration. This is not true for views though.

People in my company who interract with the database do not always have access to the model but need to look at the comments inside the stored procedures (or functions). They sometimes contain valuable explanations.

I'd be grateful if you find time to look into the issue.

**Comment by fubar-coder** [comment] 2018-11-18 16:19
It was a design decision at that time to omit the comments to get only the raw SQL code. When the ADO.NET driver (or SQL Server 2017) can handle those, then we can pass them through.

**Comment by theexar** [comment] 2018-11-18 17:47
Hello, @fubar-coder ! Thanks for your quick reply.

To be honest, I don't understand how the ADO.NET driver is unable ot handle comments in stored procedures. Can you explain? I just managed to create a procedure with comments using pure ADO.NET and everything works as expected. (Updated the repository in the first post.)

Am I missing something?

**Comment by fubar-coder** [comment] 2018-11-19 07:46
I'm not sure any more, but I was under the impression that some older ADO.NET drivers for other databases (Firebird?) didn't support comments very well.

**Comment by igitur** [comment] 2018-11-19 14:31
Is this maybe why, after upgrading to FM 3, this script:

```sql
select
  name  
into
  #primaryKeys
from 
  sys.key_constraints
where 
  [type] = 'PK' AND OBJECT_NAME(parent_object_id) = 'User'
```
is executed as

```sql
select
  name  
into
  
from 
  sys.key_constraints
where 
  [type] = 'PK' AND OBJECT_NAME(parent_object_id) = 'User'
```
?

Notice that the reference to the temporary table `#primaryKeys` is omitted.

**Comment by igitur** [comment] 2018-12-11 11:44
I have some quite complicated views and stored procs, and as every good developer knows, commenting your code is very important. Yes, I can go back to my actual migrations and look at the comments there, but it would really be useful to have the comments at the place where they are actually executed.

How about making the stipping of comments a user-supplied flag?

**Comment by igitur** [comment] 2019-01-11 09:33
@fubar-coder How do you feel about my previous comment? I'll prepare a PR if you agree to the adding of a user-supplied flag.

**Comment by fubar-coder** [comment] 2019-01-14 08:57
@igitur Sure, I'd accept this PR.

**Comment by igitur** [comment] 2019-01-14 11:02
```c#
{
    "strip|strip-comments",
    "Strip comments from the SQL scripts. Default is true.",
    v => { StripComments = v != null; }
},
```

Oh, so this already exists? Why hasn't anybody mentioned this yet?

**Comment by igitur** [comment] 2019-01-14 11:09
In all the runners, there is already a flag for stripping comments, but they're defaulted to `true`. As far as I can tell, there is no way to falsify them, because if the flag is provided, its value is set to `true` and if the flag is ommitted, the default value of `true` is also used. Am I right? I would propose that the default value just be set to `false`.

```c#
[Option("--strip", Description = "Strip comments from the SQL scripts. Default is true.")]
public bool StripComments { get; } = true;
```

**Comment by igitur** [comment] 2019-01-15 11:08
`--no-strip` doesn't have any effect. I tried both `FluentMigrator.Console` and `FluentMigrator.DotNet.Cli` runners.

The former just ignores `--no-strip`, but the latter actually writes out `Unrecognized option '--no-strip'`.

**Comment by chris-hammons** [comment] 2019-01-16 16:32
@fubar-coder 
The `strip` functionality does not seem to have been released yet. I can see it on a commit on the develop branch, but not on the master branch yet.
https://github.com/fluentmigrator/fluentmigrator/commit/1fba42358197edcf16ec45ea6f627cb2edc490bd

Do you have a timeline for releasing this change to the `FluentMigrator.DotNet.Cli` tool?

**Comment by jzabroski** [comment] 2019-02-12 20:03
@igitur  The core of the problem is this logic/invariant in the FM system around handling Batch parsing: https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/test/FluentMigrator.Tests/Unit/BatchParser/RangeSearcherTests.cs

**Comment by jzabroski** [comment] 2019-02-12 20:10
See also my comments in https://github.com/fluentmigrator/fluentmigrator/issues/945 which I now realize are closely related to the issues in this ticket.

**Comment by jzabroski** [comment] 2019-04-09 18:50
This is becoming a critical issue for us.  We can't upgrade FluentMigrator to 3.x until this is resolved.

**Comment by jzabroski** [comment] 2019-04-09 18:54
@fubar-coder  Would you be willing to accept a PR to https://github.com/fluentmigrator/fluentmigrator/tree/v3.1.3 and then create a new v3.1.4 branch and package for us?  I'll donate $50 for your trouble.  I'll literally do everything including merge your existing v4 work into v3.1.3 head

**Comment by jzabroski** [comment] 2019-04-09 22:15
I started integrating https://github.com/fluentmigrator/fluentmigrator/commit/e00485b0adc56a9435bb5425aeb5f04b564c8b0f and https://github.com/fluentmigrator/fluentmigrator/commit/1fba42358197edcf16ec45ea6f627cb2edc490bd

I finished https://github.com/fluentmigrator/fluentmigrator/commit/1fba42358197edcf16ec45ea6f627cb2edc490bd in my local against v3.1.3

**Comment by jzabroski** [comment] 2019-04-09 22:25
Here is my current progress - I haven't tested ANYTHING so far.  I just tried to quickly do a code spike and reverse integrate the master branch changes on top of the v3.1.3 tag

https://github.com/jzabroski/fluentmigrator/tree/v3.1.4

**Comment by fubar-coder** [comment] 2019-04-10 09:04
You don't need to donate for this work as I'm not doing this for money :).
The changes are looking good/sensible. Can you plkease create a PR? Thank you.

**Comment by fubar-coder** [comment] 2019-04-15 13:08
Fixed by PR #925

**Closed** 2019-04-15 13:07 UTC
Labels: by-design, complexity:low, db:sql-server, discussion

**Comment by fubar-coder** [comment] 2019-04-15 18:22
@jzabroski  3.2.0 is released

**Comment by theexar** [comment] 2019-04-16 07:50
Hello. Thanks to everybody involved in fixing the issue.

How do I disable comments strip when using the FluentMigrator.DotNet.Cli? I can't seem to be able to set StripComments to false from the command line.

**Comment by fubar-coder** [comment] 2019-04-16 10:21
Version 3.2.1 should be out within the next 10 minutes. You'll be able to disable the comments using `dotnet-fm` by adding the option `--strip:false`.

**Comment by igitur** [comment] 2019-04-16 11:42
@fubar-coder Surely `--strip:false` should **enable** comments?

**Comment by fubar-coder** [comment] 2019-04-16 13:02
@igitur Yes, my wording was wrong.

**Comment by jzabroski** [comment] 2020-02-13 18:37
FYI, I updated the dotnet-fm docs to include this parameter just now.

**Comment by igitur** [comment] 2020-08-25 09:55
For anyone else coming here, to disable the stripping of comments in `FluentMigrator.Console`, use the `--strip-` flag (notice the `-` at the end).

**Comment by jzabroski** [comment] 2020-08-25 12:50
That's weird.  I never noticed that.  Will have to check that.  Created a doc ticket. https://github.com/fluentmigrator/documentation/issues/30

**Comment by jzabroski** [comment] 2021-08-03 20:16
Docs updated.  @igitur Thanks for the explanation.

**Comment by PureKrome** [comment] 2023-12-05 11:05
Late to the party 🥳 but big thanks for adding in this option. I need comments everywhere so making sure they stay in the migration was a deal breaker, if this option wasn't here.

so thanks for adding it!
