### ISSUE TITLE
Moving to a different CI/CD service

### ISSUE THREAD

**Issue by fubar-coder** [fluentmigrator/fluentmigrator#1061] opened 2019-09-11 17:46 UTC
We're currently having problems with Travis-CI and are thinking about moving to a different service.

Some options are:

- GitHub Actions
- Azure Pipelines

What we need is:

- Build
- Test
  - Integration tests with different databases
- Deploy

I'm currently testing GitHub Actions and @eloekset volunteered to test Azure Pipelines.

Comments? Ideas? Alternatives?

**Comment by eloekset** [comment] 2019-09-11 19:10
I created a new feature branch at my fork to start testing Azure Pipelines CI. I based it on the develop branch, but it doesn't build. Don't we use the develop branch? Should I rebase on master instead, which builds fine locally?

**Comment by eloekset** [comment] 2019-09-11 19:33
The first build ran successfully in 2m 36s.
![image](https://user-images.githubusercontent.com/791721/64728371-16fb3900-d4db-11e9-919d-fd6e57bb095e.png)

Tests took 18s and 4,285 out of 4,715 succeeded. 430 tests were skipped, and those are the integration tests, I guess. Next up is to test docker images with the tools needed to run integration tests.
![image](https://user-images.githubusercontent.com/791721/64728509-65a8d300-d4db-11e9-9d72-6c85fcc1b3cd.png)

I created a new DevOps organization for this test, so I can invite others if anyone is interested. The project URL is: https://dev.azure.com/githubeloekset/fluentmigrator/

**Comment by jzabroski** [comment] 2019-09-12 00:37
Wow, this is great.

**Comment by jzabroski** [comment] 2019-09-27 19:21
So... I like Azure DevOps.  It's only obvious weakness is it doesn't support lifecycles.  But for an open source project, I don't see a need for lifecycles.  Our lifecycle is, quite literally, the build pipeline.

**Comment by eloekset** [comment] 2019-09-27 20:00
Sorry, but I haven't had time to do much the last two weeks. But hopefully I'll catch up again this weekend. I started copying the step of the Travis yaml file, since I assume that's what's used for NuGet release builds today?

**Comment by eloekset** [comment] 2019-09-28 12:26
BTW this [blog post](https://dev.to/itnext/the-ultimate-free-ci-cd-for-your-open-source-projects-3bkd) about the ultimate CI/CD for open source popped up in my newsfeed somewhere this week. Also GitHub Actions is mentioned.

**Comment by BigYellowHammer** [comment] 2019-10-01 11:22
I know it's a different topic, but what do you think guys about connecting some static code analysis tool to FM codebase?
Recently I was playing a bit with it and was able to connect Azure Pipelines with SonarCloud.
Here are the results for latest master
https://sonarcloud.io/dashboard?id=BigYellowHammer_fluentmigrator

Here is yml that does that:
https://github.com/BigYellowHammer/fluentmigrator/blob/master/azure-pipelines.yml

I was struggling with getting correct version propagated to SonarCloud so I decided to hardcode it, but we might work together to solve it if you want

**Comment by fubar-coder** [comment] 2019-10-01 12:23
Static analysis tools seem to produce more false positives than showing real problems, but **maybe** they've become better.

**Comment by BigYellowHammer** [comment] 2019-10-01 12:40
Maybe take a look on the SonarCloud results that i linked and assess yourself how valid they are. I noticed that code coverage calculations are not ideal as some classes are not being counted, but we might also try to investigate the reason.

**Comment by jzabroski** [comment] 2019-10-01 13:08
The main thing I want to do is run the Resharper Command Line
cleanupcode.exe.

Resharper really helps adopt the latest language features.

**Comment by BigYellowHammer** [comment] 2019-10-01 15:31
@jzabroski - did that :)

https://github.com/BigYellowHammer/fluentmigrator/commit/97cf443a064aac8f2766f09b88cccff3c3d7e99b

Tests are still passing, but the number of changes is overwhelming - want me to issue PR from it?

**Comment by jzabroski** [comment] 2019-10-01 15:41
I would sync up with Mark and his develop branch for that effort.  I joined Mark as a co-maintainer around March, and he is still ahead of me.  The main thing I've been helping with is code reviews and "product management" in terms of making sure new features requested make sense.  Once I catch up to FluentMigrator 4.0 I'll probably be commiting more code myself, but for now, he is the major person impacted by a refactor.

**Comment by fubar-coder** [comment] 2019-10-02 06:53
Some of the changes are strange and I don't want to merge them in its current state.

**Comment by jzabroski** [comment] 2019-10-02 13:11
We can configure cleanupcode.exe to not do those things, I think. You have to generate the configuration file through Visual Studio UI,click export,then pass it on the command line. It can then be setup as a solution wide setting.

**Comment by fubar-coder** [comment] 2019-10-02 16:21
Ok, the `#if NETFRAMEWORK` wasn't removed. It was moved. Other than that, it **does** seem useful to have a consistent code style.

**Comment by jzabroski** [comment] 2019-10-02 16:23
So, getting back on track - The CI piece here is automated.  But we don't have a CD piece, as evidenced by the fact I pushed some merges into master and Nuget hasn't automatically been pushed with a new package.

Did Travis CI do CD?  I always assumed we never actually automated CD, and it was a password on your local box.

**Comment by fubar-coder** [comment] 2019-10-02 20:32
@jzabroski It does the deployment, but **only** under the following conditions:

- Releases: For commits on the master branch, tagged with `v\d+(\.\d+)+`
- Prereleases: Commits on `release/.*` and `develop` branches

But I don't know why the travis.org didn't start a build, but I guess that it might be related to the the `Build pushed branches` configuration option, which is disabled.

**Comment by jzabroski** [comment] 2019-10-03 17:10
Travis broke again today.  I think their approach is not scalable: https://travis-ci.org/fluentmigrator/fluentmigrator/builds/593143378?utm_medium=notification&utm_source=email

> The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .

The fact they build on quicksand is just a red flag for me.  How can they not have stable debian package mirrors?

**Comment by eloekset** [comment] 2019-10-03 18:07
Interesting for me to know what conditions make a release or prerelease. I'm working on that part for the Azure Pipelines CI/CD now, but I don't push to the regular feeds yet, only a new private Azure Artifacts feed while doing test runs.

![image](https://user-images.githubusercontent.com/791721/66151980-b8783500-e618-11e9-9049-12c887454a94.png)

Currently failing on authorization to the new feed. And I need to fix a file version issue and squash all the commits of my feature branch. Azure Release Pipelines can have several stages, where one is the new feed (if we want to keep it for future testing), second can be MyGet and third the official NuGet feed.

**Comment by eloekset** [comment] 2019-10-03 18:09
And I haven't started on the fun part yet - integration tests on docker... Just running unit tests so far.

**Comment by jzabroski** [comment] 2019-10-03 18:27
@eloekset This is fantastic and we're all learning from you.

One question I've been puzzled by: What does the "@Number" mean in the pipelines.yaml?  At first I thought it was a total ordering operation, but now I'm thinking it's almost like a version number.  If it's a version number, where can we see "available versions" and "update to latest" feature in the UI?

**Comment by eloekset** [comment] 2019-10-03 18:43
I've come to the same conclusion. I use GUI to add tasks to the yaml file, and then the latest version is used by default. I can't even find a way to add older versions. (Not that I want to.) So I guess it's just a way to store the task versions so nothing breaks when new versions become available.

**Comment by jzabroski** [comment] 2019-10-06 12:44
This is awesome, but as part of this, we should fix the MSBuild pack to also pack its Tools dependencies. Without these transitive dependencies, MSBuild.exe cannot find them.

**Comment by eloekset** [comment] 2019-10-06 12:56
Are you referring to the MSBuild runner NuGet package? https://github.com/fluentmigrator/fluentmigrator/tree/master/src/FluentMigrator.MSBuild

I can see there's a readme file in that directory, saying somthing about missing assemblies. #893 is probably the issue I should refer to?

**Comment by eloekset** [comment] 2019-10-06 18:21
I don't have any good suggestions on what do to with the 893 issue, so I think I'll continue focusing on automating release of NuGet packages to MyGet and NuGet, and then fix the triggers so that another build pipeline is used for PRs instead of the default one. (I thought I already did, but apparently the branch triggers don't work as intended). Then there's the container and integration tests challenge...

**Comment by jzabroski** [comment] 2019-10-06 18:46
Fair. I can fix it.

**Comment by eloekset** [comment] 2019-10-08 20:19
I'm trying to fix the branch triggers and test artifacts filter for various release stages (internal feed, MyGet feed, NuGet feed) in the release pipeline now.

Currently I've added another yml file for a new build pipeline for PRs without all the NuGet tasks, so that it only builds and runs tests. But it seems like I don't have permissions to define new build pipelines for the project. I've requested access from the GitHub connection page, and someone should have received an email.

If we don't figure out the access issue, maybe @fubar-coder has access to create a new pipeline and associate it with the new yml file in a feature branch as shown here:
![image](https://user-images.githubusercontent.com/791721/66429943-6587ee80-ea19-11e9-9d92-d505b7ef9d4c.png)

**Comment by jzabroski** [comment] 2019-10-08 22:13
@eloekset I see.  It appears while you are a project administator on Azure DevOps, and you are an administrator on GitHub.  But it's possible you are using different identity's for each service, which is likely a no-no.

https://dev.azure.com/fluentmigrator/fluentmigrator/_settings/

https://github.com/orgs/fluentmigrator/teams/administrators

@fubar-coder I notice I am co-maintainer vs. Administrator.  What's the difference in GitHub between being an Admin and having Write access?

Similarly, and this is confusing for me: I can view all project settings on Azure DevOps for FluentMigrator, and I can even add administrators to the FluentMigrator Team, but I don't show up as an Administrator.  

It's possible this can cause gotchas for future collaborators, so we should probably spend some time and understand the proper way to add people, document it, and strive for consistency to avoid these annoyances.

**Comment by jzabroski** [comment] 2019-10-16 23:28
Related: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml

**Comment by jzabroski** [comment] 2019-10-17 16:11
1. Went to https://dev.azure.com/fluentmigrator/_apis/projects/fluentmigrator
2. Grabbed projectId
3. Plugged fluentmigrator, 22b31067-b424-416b-b89f-682210a37a55, and 1 into the shield generator
4. ???
5. PROFIT

https://img.shields.io/azure-devops/build/fluentmigrator/22b31067-b424-416b-b89f-682210a37a55/1

**Comment by eloekset** [comment] 2019-10-17 17:26
First, thanks for the build badge, @jzabroski 👍

I finally found how to create an additional pipeline. It was a bit tricky to find, so I'll document it here for later:
1. Click the connection link in the "You may also select a specific connection" line
![image](https://user-images.githubusercontent.com/791721/67032079-2f322980-f113-11e9-86f4-d44cb715a9d6.png)
2. Select the correct connection
![image](https://user-images.githubusercontent.com/791721/67032148-4a049e00-f113-11e9-9d3f-71c2f19d24eb.png)
3. Select the correct repository for that connection (if more than one)
![image](https://user-images.githubusercontent.com/791721/67032199-630d4f00-f113-11e9-982d-c271bc42d036.png)
4. Select Existing Azure Pipelines YAML file (I had already created the yml file in a feature branch)
![image](https://user-images.githubusercontent.com/791721/67032275-8cc67600-f113-11e9-99cd-19c446513406.png)
5. Select branch and file name for the yml file to be used for the new pipeline
![image](https://user-images.githubusercontent.com/791721/67032317-a5cf2700-f113-11e9-9bb4-82304b646dfd.png)

If the triggers work as intended now, we should run a different pipeline for PRs than we do for master, release/* and develop branches. The point of all this is to only build and run tests for PRs, while the other branches should produce NuGet packages.

**Comment by jzabroski** [comment] 2019-10-17 17:36
Just tested it via: telling "dependabot recreate" on the Autofac bump pull request.

**Comment by jzabroski** [comment] 2019-10-17 17:37
@eloekset here is the Autofac PR build: https://github.com/fluentmigrator/fluentmigrator/pull/1090/checks?check_run_id=264377031

**Comment by eloekset** [comment] 2019-10-17 18:48
Ok, I created a PR for the new yaml file now. Unfortunately both pipelines execute for the PR. Need to find the correct way to filter the triggers on branches. I think I follow the documentation, but there's obviously something I've missed. Will have to send a few PRs to test this, or debug it in another repository to avoid all that noice in here.

**Comment by eloekset** [comment] 2019-10-17 18:51
![image](https://user-images.githubusercontent.com/791721/67038512-d1f0a500-f11f-11e9-829b-bb8cb9b6b834.png)
Only the one named CI for PRs should get triggered.

**Comment by jzabroski** [comment] 2019-10-17 20:10
Nothing is easy.  You're going great, though.

**Comment by fubar-coder** [comment] 2019-10-26 10:22
I tinkered with Azure Pipelines and this are my findings:

# GitVersion preview simplifies some things

Extension: https://marketplace.visualstudio.com/items?itemName=gittools.usegitversion-preview

```yaml
  steps:
  - task: UseGitVersion@5
    displayName: 'GitVersion'
    inputs:
      versionSpec: '5.0.2-beta1.130'
      includePrerelease: true
      updateAssemblyInfo: false
    env:
      BUILD_BUILDNUMBER: $(GitVersion.FullSemVer)
```

The `BUILD_BUILDNUMBER` thing avoids that we have to use a script to update the build number.

# Avoiding non-PR triggers

```yaml
trigger: none

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
```

# Avoiding PR triggers

```yaml
trigger:
  branches:
    include:
    - release/*
    - develop
    - master

pr: none
```

# Installing of NuGet

This should only be necessary when we need a version different from the default version provided by Azure Pipeline.

# assemblyVersion, assemblyFileVersion, ...

Maybe we can ignore it and just:

- Set the build version to `GitVersion.SemVer`
- Let the msbuild tool chain figure out the other versions

# Windows agent

Currently, we're using a Windows VM as specified with:

```yaml
pool:
  vmImage: 'windows-latest'
```

According to the documentation ([Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
), mono should be installed on Linux VMs too.

**Comment by eloekset** [comment] 2019-10-26 18:50
Thanks @fubar-coder ! That's a lot of good findings. :)

I'll try them out the next thing I'll do.

**Comment by eloekset** [comment] 2019-10-27 10:50
The triggers now work perfectly, @fubar-coder ! 😃 

 - The PR pipeline ran for the PR of the change to the triggers itself, while the main pipeline didn't run. 
 - The main pipeline currently runs for the merge commit after completing the PR, while the PR pipeline didn't run.

![image](https://user-images.githubusercontent.com/791721/67633335-fe8a8680-f8ae-11e9-894f-497e4b7fdb76.png)

I think that's ok, and we can use release pipelines to filter how the NuGet packages are pushed based on the thoughts of @jzabroski in this https://github.com/fluentmigrator/fluentmigrator/issues/1101#issuecomment-546398620

Next up is trying to simplify the versioning by using the preview of GitVersion task. I don't have privileges to install it myself, but I've sent a request to have it installed.
![image](https://user-images.githubusercontent.com/791721/67633401-b1f37b00-f8af-11e9-8364-f61772e8f718.png)

**Comment by fubar-coder** [comment] 2019-10-27 11:19
@eloekset I approved it and I also added `Build Quality Checks`. Might come in handy.

**Comment by eloekset** [comment] 2019-10-27 12:24
Thanks! The preview of UseGitVersion task has a different configuration than the older one. I'm into testing the version number stuff now. So far it looks like I'm back to the same issues I had, which made me set assemblyVersion and assemblyFileVersion explicitly. I'm not sure why it works differently from the Travis build. But I'll try some more before I conclude.

BTW, we still need the NuGetToolsInstaller task. Without specifying any parameters, it gives us version 5.3.1 of NuGet right now, and the default version is 4.1, which isn't capable of doing a restore command for our solution. Build log when running with the default version of NuGet: 
[12.txt](https://github.com/fluentmigrator/fluentmigrator/files/3775822/12.txt)

Will have a look at Build Quality Checks after completing the build number version properties.

**Comment by eloekset** [comment] 2019-10-27 16:45
The SemVer stuff is now merged to master, ref PR #1106. I'm exited to see how this works with the NuGet "quality of release" feature of Azure Artifacts.

The PR pipeline now takes 3m9s compared to the Travis build, that takes 12m17s. To be fair, the NuGet stuff is removed from the PR pipeline, and we still need to add back integration tests. The main build pipeline, without integration tests, now takes 5m54s.

So, for the build agent OS, do you think it's OK to continue on "windows-latest" or should we switch to Linux and build on mono instead? Now we use .NET Core CLI for everything except running tests (and building for tests).

**Comment by fubar-coder** [comment] 2019-10-27 18:05
We should use `windows-latest` for the following reasons:

1. `VSBuild` and `VSTest` are (IIRC) Windows-only due to the reliance on PowerShell scripts
2. Warnings aren't properly captured when using `dotnet build` (see issue Microsoft/azure-pipelines-tasks#7749)

**Comment by eloekset** [comment] 2019-10-29 18:14
@fubar-coder @jzabroski this may be an interesting webinar for us: https://goto.docker.com/webinar-database-devops-with-containers.html
It begins in 45 minutes. I'll be attending.

**Comment by eloekset** [comment] 2019-10-29 20:16
This webinar is a great kick-start for our container integration testing. Sample docker file here: https://github.com/robrich/database-devops-with-containers/blob/master/Database/Dockerfile

And the slides from the webinar here: https://robrich.org/slides/database-devops-with-containers/#/

He's also got a repo from a workshop about DevOps pipelines for .NET apps and databases, which is right up our alley 🎆 https://github.com/robrich/DevOps-Pipeline-for-.NET-Apps-and-Databases-Workshop

**Comment by jzabroski** [comment] 2019-10-29 20:47
Thanks for attending this.  Would you believe it, we had a firedrill kick off in our building at exactly 2pm est when the webinar started?  LOL

**Comment by fubar-coder** [comment] 2019-10-29 22:06
I missed it, because I was out with friends 🎉 .

The `sleep 80` in the docker file looks frightening, but I'll definitely take a look at the repository and the slides.

**Comment by jzabroski** [comment] 2019-10-29 22:11
I think it's just an early prototype.  2020 is definitely the year DevOps invades databases, and I think FluentMigrator can be the industry leader there - seriously.

**Comment by ikudjoi** [comment] 2019-11-08 13:19
Hi, I just talked with a local Snowflake representative and asked whether an Open Source project like this could gain access to a free account for integration testing. I was told to formally ask for one by email. Before doing that I could ask where that account should be geographically located, are these Azure Pipelines tied to some geographical location in any way?

Also please suggest if this is a bad idea. I tried to get a clue what's the status of integration testing atm but wasn't able quickly to discover that yet. Just went to Azure DevOps site for the first time, I'm familiar with GitLab only.

**Comment by jzabroski** [comment] 2019-11-08 14:22
That's an awesome idea. I tried to contact their sales team about a major
limitation in their SQL language that prevented me from writing a
Snowflakedb provider for EF Core. I absolutely LOVE Snowflakedb but it
doesn't support scope identity.

Maybe once we have a working relationship with them there can be progress
made there.

**Comment by eloekset** [comment] 2019-11-10 10:49
@ikudjoi thank's for the idea! I haven't heard about them before. Our Azure DevOps organization is located in West Europe, which is Amsterdam. This is the [map of all current Azure regions](https://azure.microsoft.com/nb-no/global-infrastructure/regions/).

**Comment by ikudjoi** [comment] 2019-11-10 19:42
That's exactly the information I asked for, thanks! I'm now writing a request to the local Snowflake representative.

**Comment by vasundhara-b** [comment] 2022-03-07 19:06
any release pipeline steps to release to sql server?

**Comment by jzabroski** [comment] 2022-03-07 19:52
@vasundhara-b I don't think your question belongs in this thread.  At any rate, 9 words is not a feature request.  Please open a new issue and follow the issue template describing what problem you're trying to solve.

**Comment by vasundhara-b** [comment] 2022-03-08 09:55
ok thank you

**Closed** 2022-05-05 15:25 UTC
Labels: discussion
