### ISSUE TITLE
Support for ServicePrincipal authentication

### ISSUE THREAD

**Issue by tauqirghani** [fluentmigrator/fluentmigrator#1051] opened 2019-08-12 18:02 UTC
Is there a way to add the AccessToken received from ServicePrincipal authentication to the SqlServer connection object?

**Comment by fubar-coder** [comment] 2019-08-13 07:16
Duplicate of #989.

TL/DR: It's not supported yet.

**Closed by fubar-coder** 2019-08-13 07:16 UTC
